// dsh-locale-ru — русский интерфейс для DeepSeek Harness.
// Клиентская половина плагина: регистрирует русские словари, добавляет "ru"
// в список языков, хранит выбор локально (схема настроек хоста принимает
// только zh/en) и включает русский, когда браузер предпочитает его или
// пользователь выбрал его ранее (localStorage).
window.__ModuleLoader__.load({
  id: "@dsh-local/locale-ru",
  factory: function (require) {
    var module = { exports: {} };
    var exports = module.exports;

    var RU = {
      "command": {
        "listbox.aria": "/{command} совпадений",
        "notice.imagesUnsupported": "/{command} не принимает вложения с изображениями; сначала удалите их",
        "overlay.aria": "Параметры /{command}",
        "search.aria": "Фильтровать параметры",
        "search.placeholder": "Поиск…",
        "status.applying": "Применение…",
        "status.empty": "Нет параметров",
        "status.loading": "Загрузка параметров…"
      },
      "common": {
        "back": "Назад",
        "cancel": "Отмена",
        "close": "Закрыть",
        "collapse": "Свернуть",
        "copied": "Скопировано",
        "copy": "Копировать",
        "delete": "Удалить",
        "edit": "Изменить",
        "expand": "Развернуть",
        "load.failed": "Не удалось загрузить",
        "loading": "Загрузка…",
        "more": "Ещё",
        "next": "Далее",
        "none": "Нет",
        "ok": "ОК",
        "previous": "Назад",
        "retry": "Повторить",
        "save": "Сохранить",
        "search": "Поиск",
        "skip": "Пропустить",
        "submit": "Отправить",
        "submitting": "Отправка…",
        "truncated": "Обрезано",
        "unknown": "Неизвестно"
      },
      "cordis": {
        "a11y.defining": "Определение плагина",
        "a11y.failed": "Не удалось определить",
        "a11y.stopped": "Определение прервано",
        "action.approve": "Разрешить",
        "action.approveOnce": "Разрешить только эту версию",
        "action.approvePlugin": "Разрешить будущие версии этого плагина",
        "action.decline": "Отклонить",
        "action.remove": "Удалить",
        "action.retry": "Повторить",
        "action.rollback": "Откатить",
        "action.run": "Запустить",
        "action.stop": "Остановить",
        "body.clientCode": "Клиент",
        "body.copied": "Скопировано",
        "body.copy": "Копировать",
        "body.hostCode": "Хост",
        "body.output": "Результат",
        "body.source": "Исходный код плагина",
        "panel.approvals.aria": "Разрешения Cordis",
        "panel.current": "Текущий: {packageId}",
        "panel.empty": "Плагины ещё не определены",
        "panel.group.current": "Эта сессия",
        "panel.group.others": "Другие сессии",
        "panel.hint": "Элементы управления запуском находятся на панели Cordis над «Настройками»",
        "panel.loading": "Чтение…",
        "panel.next": "Далее: {packageId}",
        "panel.plugins.aria": "Плагины Cordis",
        "panel.readFailed": "Не удалось прочитать список плагинов: {message}",
        "panel.runningCount": "Запущено: {count}",
        "panel.title": "Плагины Cordis",
        "panel.trigger": "Плагин Cordis",
        "panel.version": "Версия",
        "purpose.missing": "(назначение не указано)",
        "render.failedAbdicated": "Не удалось отобразить {slot}; восстановлен интерфейс по умолчанию:",
        "render.failedHeld": "Не удалось отобразить {slot}:",
        "row.defineTitle": "Зарегистрировать плагин Cordis",
        "row.removeTitle": "Удалить плагин Cordis",
        "row.runTitle": "Запустить плагин Cordis",
        "row.stopTitle": "Остановить плагин Cordis",
        "row.updateTitle": "Обновить плагин Cordis",
        "run.removed": "Этот пакет больше не существует",
        "run.superseded": "Ниже доступна карточка более нового запуска",
        "status.awaitingApproval": "Ожидает одобрения",
        "status.clientPending": "Клиент готов к активации",
        "status.failed": "Запуск не удался",
        "status.idle": "Готов",
        "status.removed": "Удалено",
        "status.running": "Выполняется",
        "status.superseded": "Доступен более новый запуск"
      },
      "deliverables": {
        "produced.label": "Создано",
        "produced.more": "+ {count} файлов",
        "produced.moreOne": "+ 1 файл",
        "produced.open": "Открыть {name}",
        "produced.showInFolder": "Показать в папке"
      },
      "feedback": {
        "action.dislike": "Плохой ответ",
        "action.dislikeActive": "Убрать оценку",
        "action.like": "Хороший ответ",
        "action.likeActive": "Убрать оценку",
        "error.conflict": "Этот отзыв был изменён в другом месте; показано актуальное состояние",
        "error.generic": "Не удалось сохранить отзыв",
        "error.load": "Не удалось загрузить отзыв",
        "note.aria": "Заметка к отзыву",
        "note.cancel": "Отмена",
        "note.dialog": "Отзыв",
        "note.open": "Добавить заметку",
        "note.placeholder": "Что было хорошо или что пошло не так? (необязательно)",
        "note.save": "Сохранить"
      },
      "goal": {
        "action.cancel": "Отменить изменение",
        "action.clear": "Очистить цель",
        "action.edit": "Изменить цель",
        "action.pause": "Поставить цель на паузу",
        "action.resume": "Возобновить цель",
        "action.save": "Сохранить цель",
        "commandInput.aria": "Ввод команды",
        "objective.aria": "Цель",
        "phase.active": "Активная цель",
        "phase.blocked": "Заблокированная цель",
        "phase.paused": "Приостановленная цель"
      },
      "model": {
        "action.reload": "Перезагрузить",
        "blocked.composer": "Эта модель недоступна — выберите другую, чтобы продолжить",
        "command.description": "Выбрать модель для этого диалога",
        "effort.providerDefault": "По умолчанию",
        "empty.efforts": "Эта модель не предоставляет уровней усилий рассуждения.",
        "empty.models": "Нет доступных моделей.",
        "error.action": "Операция с моделью не удалась: {message}",
        "menu.aria": "Модель и усилия рассуждения",
        "menu.effort": "Усилия",
        "menu.model": "Модель",
        "option.loadError": "Не удалось загрузить каталог: {message}",
        "status.loading": "Обновление списка моделей…",
        "trigger.aria": "Выбрать модель, текущая: {model}",
        "trigger.ariaEffort": "Выбрать модель, текущая: {model}, усилия рассуждения: {effort}",
        "trigger.fallback": "Выбрать модель",
        "trigger.selectAria": "Выбрать модель",
        "warning.groupLoad": "Не удалось загрузить {name}: {message}"
      },
      "plan": {
        "chip.off.aria": "Режим планирования выключен, нажмите, чтобы включить",
        "chip.off.title": "Режим планирования выключен — нажмите, чтобы включить (/plan)",
        "chip.on.aria": "Режим планирования включён, нажмите, чтобы выключить",
        "chip.on.title": "Режим планирования включён — нажмите, чтобы выключить (/plan off)"
      },
      "question": {
        "action.next": "Далее",
        "action.skip": "Пропустить этот вопрос",
        "custom.placeholder": "Введите ответ",
        "error.incomplete": "Сначала ответьте на этот вопрос.",
        "error.unanswered": "Выберите вариант или введите свой ответ.",
        "nav.cancel": "Закрыть все вопросы",
        "nav.maximize": "Развернуть карточку вопроса",
        "nav.minimize": "Свернуть карточку вопроса",
        "nav.next": "Следующий вопрос",
        "nav.prev": "Предыдущий вопрос",
        "option.recommended": "Рекомендуется",
        "plan.approve": "Одобрить",
        "plan.decline": "Отклонить",
        "plan.discuss": "Обсудить",
        "plan.header": "Проверка плана"
      },
      "reference": {
        "candidate.file": "Файл",
        "candidate.folder": "Папка",
        "candidate.noCwd": "(нет рабочей папки)",
        "candidate.session": "Сессия",
        "section.files": "Файлы и папки",
        "section.sessions": "Диалоги сессий"
      },
      "session-log-download": {
        "dialog.close": "Закрыть",
        "dialog.commandFailed": "Не удалось начать экспорт сессии.",
        "dialog.errorTitle": "Экспорт сессии не удался",
        "dialog.preparingDescription": "Подготовка ZIP-архива с этой сессией, её подсессиями и вложениями.",
        "dialog.preparingTitle": "Экспорт сессии",
        "dialog.successDescription": "Браузер загружает ZIP-архив сессии.",
        "dialog.successTitle": "Загрузка сессии началась"
      },
      "settings": {
        "close": "Закрыть",
        "general.nav": "Общие",
        "openDocument": "Открыть файл конфигурации",
        "openDocument.error": "Не удалось открыть файл конфигурации",
        "title": "Настройки",
        "trigger": "Настройки"
      },
      "settings.locale": {
        "language.title": "Язык"
      },
      "sidebar": {
        "session.new": "Новая сессия",
        "session.new.label": "Новая сессия",
        "toggle.collapse": "Свернуть боковую панель",
        "toggle.open": "Открыть боковую панель"
      },
      "skill": {
        "menu.userOnly": "только для пользователя",
        "row.failed": "Не удалось загрузить навык",
        "row.instructions": "Инструкции",
        "row.running": "Загрузка навыка",
        "row.stopped": "Загрузка навыка остановлена"
      },
      "subagent": {
        "activity.inactive": "не выполняется",
        "activity.running": "выполняется",
        "branch.collapse": "Свернуть подчинённые элементы {label}",
        "branch.expand": "Развернуть подчинённые элементы {label}",
        "count.running.one": "Выполняется {count} субагент",
        "count.running.other": "Выполняется {count} субагентов",
        "count.total.one": "{count} субагент",
        "count.total.other": "{count} субагентов",
        "diagnostic.corrupt": "повреждённая запись сессии",
        "diagnostic.unavailable": "запись сессии временно недоступна",
        "diagnostic.unsupported": "неподдерживаемая версия записи субагента",
        "duration.days": "{days} дн",
        "duration.daysHours": "{days} дн {hours} ч",
        "duration.exactDays": "{days} дн {hours} ч {minutes} мин {seconds} с",
        "duration.exactTitle": "Общая продолжительность: {duration}",
        "duration.hours": "{hours} ч {minutes} мин {seconds} с",
        "duration.minutes": "{minutes} мин {seconds} с",
        "duration.months": "~{months} мес",
        "duration.monthsDays": "~{months} мес {days} дн",
        "duration.seconds": "{seconds} с",
        "duration.years": "~{years} г",
        "duration.yearsMonths": "~{years} г {months} мес",
        "load.error": "Не удалось загрузить субагентов",
        "loading.aria": "Загрузка субагентов",
        "loading.label": "Загрузка субагентов…",
        "mode.continuable": "продолжаемый",
        "mode.oneShot": "одноразовый",
        "readonly.body": "Родительская сессия недоступна; откройте её, чтобы продолжить отправку сообщений.",
        "readonly.oneShot.body": "Одноразовые задачи не принимают уточнений; просмотрите полную запись выполнения здесь.",
        "readonly.oneShot.title": "Запись одноразового субагента",
        "readonly.title": "Этот субагент сейчас доступен только для чтения",
        "retry": "Повторить",
        "switcher.aria": "Переключить субагента: {title}",
        "tree.aria": "Сессии субагентов"
      },
      "trajectory": {
        "toolbar.actualTime": "Фактическое время",
        "toolbar.aria": "Панель траектории",
        "toolbar.calls": "Вызовы",
        "toolbar.collapseCalls": "Свернуть вызовы",
        "toolbar.collapseTurns": "Свернуть шаги",
        "toolbar.duration": "Продолжительность",
        "toolbar.expandCalls": "Развернуть вызовы",
        "toolbar.expandTurns": "Развернуть шаги",
        "toolbar.search": "Поиск по траектории",
        "toolbar.searchPlaceholder": "Поиск",
        "toolbar.turns": "Шаги",
        "toolbar.useActualDuration": "Использовать фактическую продолжительность",
        "toolbar.useEqualWidth": "Равная ширина операций",
        "view.trajectory": "Траектория"
      },
      "workflowRun": {
        "member.empty": "Пустое имя участника",
        "member.open": "Открыть {name}",
        "phase.empty": "Пустое имя фазы",
        "phase.unassigned": "Без фазы",
        "run.empty": "Участники не запущены",
        "run.members.one": "{count} участник",
        "run.members.other": "{count} участников",
        "run.title": "{name}",
        "status.cancelled": "Отменено",
        "status.completed": "Завершено",
        "status.failed": "Не удалось",
        "status.interrupted": "Прервано",
        "status.running": "Выполняется",
        "statusCount.cancelled": "Отменено: {count}",
        "statusCount.completed": "Завершено: {count}",
        "statusCount.failed": "Не удалось: {count}",
        "statusCount.interrupted": "Прервано: {count}",
        "statusCount.running": "Выполняется: {count}"
      },
      "workspace": {
        "actions.newSession.aria": "Новая сессия в {name}",
        "actions.session.aria": "Действия с сессией {name}",
        "actions.workspace.aria": "Действия с рабочей областью {name}",
        "conflict.named": "Рабочая область «{name}» уже существует.",
        "date.ymd": "{y}-{m}-{d}",
        "delete.desc": "Это удалит «{name}» из списка рабочих областей. Папка и журналы сессий будут сохранены. Её сессии появятся в разделе «Без группы».",
        "delete.pending": "Удаление рабочей области…",
        "delete.workspace": "Удалить рабочую область",
        "empty.noMatches": "Ничего не найдено",
        "empty.none": "Сессий пока нет",
        "field.sessionName": "Имя сессии",
        "field.workspaceName": "Имя рабочей области",
        "folderError.retry": "Выбрать снова",
        "folderError.title": "Не удалось открыть папку",
        "group.ungrouped": "Без группы",
        "groupBy.flat": "Одним списком",
        "groupBy.label": "Группировать по",
        "groupBy.workspace": "Рабочая область",
        "hover.copied": "Скопировано",
        "hover.created": "Создано {time}",
        "menu.addWorkspace": "Добавить рабочую область…",
        "menu.archiveSession": "Архивировать сессию",
        "menu.fork": "Разветвить сессию",
        "orderBy.label": "Сортировать по",
        "orderBy.manual": "Вручную",
        "orderBy.updated": "По дате изменения",
        "picker.loading": "Загрузка рабочих областей…",
        "rename": "Переименовать",
        "rename.session.title": "Переименовать сессию",
        "rename.workspace.title": "Переименовать рабочую область",
        "search.clear": "Очистить поиск",
        "search.hasMore": "Показаны первые {n} результатов. Уточните поиск.",
        "search.noMatches": "Сессии не найдены",
        "search.pending": "Поиск по истории сессий…",
        "search.placeholder": "Поиск сессий...",
        "search.results.aria": "Результаты поиска",
        "search.sessions.aria": "Поиск сессий",
        "search.unavailable": "Поиск по содержимому временно недоступен. Показаны совпадения по имени.",
        "section.sessions": "Сессии",
        "section.workspaces": "Рабочие области",
        "session.new": "Новая сессия",
        "sessions.collapse": "Показать меньше",
        "sessions.count.one": "{n} сессия",
        "sessions.count.other": "{n} сессий",
        "sessions.expand": "Показать ещё {n} сессий",
        "status.completed": "Завершено",
        "status.idle": "Ожидает",
        "status.planReview": "План ожидает проверки",
        "status.running": "Выполняется",
        "status.subagentsRunning.one": "Выполняется {n} субагент",
        "status.subagentsRunning.other": "Выполняется {n} субагентов",
        "status.waitingAnswer": "Ожидание ответа",
        "status.waitingApproval": "Ожидание одобрения",
        "time.ago": "{t} назад",
        "time.days": "{n} дн",
        "time.hours": "{n} ч",
        "time.minutes": "{n} мин",
        "time.months": "{n} мес",
        "time.now": "только что",
        "time.years": "{n} г",
        "viewOptions.label": "Параметры просмотра",
        "workspace.add": "Добавить рабочую область"
      },
      "agent-presets": {
        "brokenBadge": "Не удалось загрузить",
        "brokenNoCopy": "Не удалось дублировать пресет, который не загрузился",
        "builtIn": "Встроенный",
        "builtInGroup": "Встроенные",
        "cancel": "Отмена",
        "close": "Закрыть",
        "composition": "Композиция (agent.cordis.yml)",
        "copyIntro": "Пресет полностью копируется на этой машине. Идентификатор становится именем каталога и позже не меняется; всё остальное редактируется в собственных файлах пресета.",
        "copyOf": "Скопировано из",
        "copyTitle": "Дублировать пресет",
        "create": "Создать",
        "creating": "Создание…",
        "creatorDraft": "Создать свой пресет в режиме Creator",
        "customGroup": "Свои",
        "delete": "Удалить",
        "deleteConfirm": "Удалить",
        "deleteDescription": "Каталог пресета будет удалён. Уже запущенные на нём сессии продолжат работать; новые сессии не смогут его выбрать.",
        "deleteTitle": "Удалить этот пресет?",
        "deleting": "Удаление…",
        "description": "Применяется к сессиям, которые вы начнёте с этого момента. Запущенные сессии сохраняют пресет, с которым были начаты.",
        "displayName": "Название",
        "displayNamePlaceholder": "Показывается в списке; по умолчанию — идентификатор",
        "duplicate": "Дублировать",
        "duplicateUnavailable": "В этой установке нет каталога пресетов для записи",
        "error": "Не удалось загрузить пресеты агентов.",
        "headerHint": "Пресет агента, с которым запущена эта сессия (зафиксирован при старте)",
        "idInvalid": "Используйте строчные буквы, цифры и дефисы, начиная с буквы или цифры.",
        "idRequired": "Задайте идентификатор пресета.",
        "idTaken": "Пресет с таким идентификатором уже существует.",
        "inUse": "Используется",
        "loading": "Загрузка пресетов…",
        "nav": "Пресеты агентов",
        "noDescription": "Без описания.",
        "openLocation": "Открыть папку",
        "presetCodeDescription": "Все возможности режима Standard, но инструменты доступны через Code Mode SDK, чтобы модель могла объединять многошаговые операции в одной TypeScript-программе.",
        "presetCodeName": "Режим PTC",
        "presetCordisDescription": "Создан для создания собственных пресетов агентов: все возможности режима Standard плюс инспекция среды выполнения, эксперименты с плагинами и подсказки по созданию пресетов.",
        "presetCordisName": "Режим Creator",
        "presetId": "Идентификатор",
        "presetIdPlaceholder": "my-agent",
        "presetMinimalDescription": "Кодинг-агент с двумя инструментами: постоянным bash и str_replace_editor.",
        "presetMinimalName": "Минимальный режим",
        "presetStandardDescription": "Полноценный кодинг-агент: редактирование файлов, терминал, поиск по файлам и вебу, навыки, планирование, цели, субагенты и воркфлоу.",
        "presetStandardName": "Стандартный режим",
        "retry": "Повторить",
        "revealedPathLabel": "Файлы пресета:",
        "seatHint": "Пресет агента для сессии, которую вы собираетесь начать",
        "sectionIntro": "Пресет — это композиция плагинов, с которой работает агент сессии: его инструменты, промпт и возможности. Дублируйте существующий и сделайте своим или попросите агента создать его в режиме Creator.",
        "setDefault": "Сделать по умолчанию",
        "showLocation": "Показать расположение",
        "title": "Пресет агента",
        "userTrust": "Свой",
        "view": "Просмотр"
      },
      "conversation": {
        "access.confirm.acknowledge": "Я понимаю риски и хочу продолжить",
        "access.confirm.cancel": "Отмена",
        "access.confirm.description": "Полный доступ сокращает шаги подтверждения и позволяет агенту выполнять больше действий напрямую, включая чувствительные операции, изменения файлов и внешние команды. Используйте его, только если доверяете текущей задаче.",
        "access.confirm.enable": "Включить полный доступ",
        "access.confirm.title": "Включить полный доступ?",
        "approval.allowOnce": "Разрешить один раз",
        "approval.detail.aria": "Детали одобрения",
        "approval.escalation": "Инструмент {toolName} запрашивает выполнение с повышенными правами",
        "approval.reject": "Отклонить",
        "approval.waiting": "Ожидание одобрения",
        "ask.answered": "Отвечено: {answered}/{total}",
        "ask.cancelled": "отменено",
        "ask.interrupted": "прервано",
        "ask.rowTitle": "Задать вопрос",
        "ask.waiting": "ожидание",
        "bash.failed": "Не удалось",
        "bash.running": "Выполняется",
        "bash.stopped": "Остановлено",
        "chat.loadError": "Не удалось загрузить историю: {message} ({code})",
        "chat.loadOlder": "Загрузить ранее",
        "chat.loadingHistory": "Загрузка истории…",
        "chat.toBottom": "Вниз",
        "clock.md": "{m}/{d}",
        "clock.ymd": "{y}-{m}-{d}",
        "command.done": "Завершено",
        "command.failed": "Команда не выполнена",
        "command.imagesUnsupported": "/{command} не принимает вложения с изображениями; сначала удалите их",
        "command.running": "Выполняется…",
        "command.title": "Команда",
        "context.aria": "Использовано {percent} контекста",
        "context.messages": "Сообщения",
        "context.system": "Системный промпт",
        "context.tools": "Инструменты",
        "context.used": "контекста использовано",
        "details.close": "Закрыть детали",
        "details.empty": "Нажмите на строку инструмента в потоке сообщений, чтобы посмотреть его детали",
        "details.input": "Ввод",
        "details.notInWindow": "Этот вызов вне текущего окна",
        "details.output": "Вывод",
        "details.running": "Выполняется…",
        "details.title": "Детали",
        "duration.minutes": "{minutes} мин {seconds} с",
        "duration.seconds": "{seconds} с",
        "fileOpen.folderTitle": "Не удалось открыть папку",
        "fileOpen.folderUnknown": "Не удалось открыть эту папку",
        "fileOpen.title": "Не удалось открыть файл",
        "fileOpen.unknown": "Не удалось открыть этот файл",
        "hero.chooseWorkspace": "Выбрать рабочую область",
        "hero.headline": "В неизведанное",
        "hero.preview": "Предпросмотр",
        "hint.goal": "опишите цель для длительной задачи",
        "hint.goal.active": "цель активна — изменить / пауза / возобновить / очистить",
        "image.closePreview": "Закрыть предпросмотр исходного изображения",
        "image.dimensionTooLarge": "Стороны изображения должны быть не больше {size}px; уменьшите его и попробуйте снова",
        "image.dropBlocked": "Сейчас нельзя добавить изображения",
        "image.dropDesc": "До {count} изображений, каждое до {size}",
        "image.dropTitle": "Перетащите изображения сюда, чтобы добавить",
        "image.fileTooLarge": "Каждое изображение должно быть меньше {size}",
        "image.label": "Изображение",
        "image.loadFailed": "Не удалось загрузить изображение; нажмите, чтобы повторить",
        "image.loading": "Загрузка изображения…",
        "image.modelUnsupported": "Текущая модель не поддерживает изображения; переключитесь на модель, которая их поддерживает",
        "image.openOriginal": "Открыть оригинал",
        "image.openOriginalLabel": "{label}, нажмите, чтобы открыть оригинал",
        "image.original": "Исходное изображение",
        "image.pending": "Ожидают отправки",
        "image.preview": "Предпросмотр исходного изображения",
        "image.remove": "Удалить изображение {name}",
        "image.scrollLeft": "Прокрутить изображения влево",
        "image.scrollRight": "Прокрутить изображения вправо",
        "image.sendFailed": "Не удалось отправить изображения ({reason}); добавьте их снова и повторите",
        "image.serviceUnavailable": "Сервис загрузки изображений недоступен",
        "image.subagentUnsupported": "Сессии субагентов пока не поддерживают изображения",
        "image.tooMany": "Сообщение может содержать до {count} изображений",
        "image.tooManyPixels": "Разрешение изображения слишком высокое; сожмите его и попробуйте снова",
        "image.totalTooLarge": "Изображения суммарно превышают {size}; удалите часть и попробуйте снова",
        "image.unsupportedType": "Поддерживаются только изображения PNG, JPG, WebP и GIF",
        "input.accessMode": "Режим доступа, текущий: {name}",
        "input.commands": "Команды",
        "input.send": "Отправить сообщение",
        "input.stop": "Остановить генерацию",
        "json.truncated": "… обрезано, всего {total} символов",
        "message.branch": "Ветвь в новый диалог",
        "message.branchUnavailable": "Доступно только для последнего сообщения завершённого шага",
        "message.compaction": "Контекст сжат",
        "message.compaction.completed": "Сжато {items} элементов истории (~{tokens} токенов)",
        "message.compaction.expand": "Показать сводку сжатия",
        "message.compaction.running": "Сжатие контекста…",
        "message.compaction.unavailable": "Сводка сжатия недоступна",
        "message.context.catalog.more": "… ещё {count}",
        "message.context.catalog.replaced": "Заменённый каталог",
        "message.context.instructions.added": "добавлено",
        "message.context.instructions.loaded": "загружено",
        "message.context.instructions.removed": "удалено",
        "message.context.instructions.updated": "обновлено",
        "message.context.recall.counts": "сохранено: {retained} · опущено: {omitted}",
        "message.context.recall.truncated": "обрезано",
        "message.context.relay.from": "Из сессии {session}",
        "message.context.snapshot.supersedes": "Заменяет более ранние снимки",
        "message.contextInjection": "Внедрение контекста",
        "message.contextRecall": "Воспоминание сессии",
        "message.extraBlock": "Дополнительный блок контента",
        "message.maxTokens": "Достигнут лимит выходных токенов",
        "message.maxTokens.hint": "Ответ был оборван; предыдущий вывод сохранён в диалоге. Отправьте «continue», чтобы модель продолжила.",
        "message.ranFor": "Выполнялось {duration}",
        "message.referenceSeparator": ", ",
        "message.referenceSummary": "Упомянутая сессия · {labels}",
        "message.retry.active": "Повтор запроса к модели",
        "message.retry.cancelled": "Повтор запроса к модели отменён",
        "message.retry.delay": "Задержка повтора: ",
        "message.retry.failure": "Причина сбоя: ",
        "message.retry.scheduled": "Ожидание повтора запроса к модели",
        "message.retry.started": "Запрос к модели повторён",
        "message.retry.status": "{label} ({retry}/{maximum}) · {seconds} с",
        "message.stopped": "Остановлено",
        "message.tokensPerSecond": "{tps} ток/с",
        "message.ttft": "TTFT {seconds} с",
        "message.turnError": "Этот шаг не удался",
        "message.unknownBlock": "Неизвестный блок контента",
        "message.unknownSurface": "Неизвестное событие поверхности: {type}",
        "placeholder.default": "Напишите агенту",
        "placeholder.hero": "Опишите, что хотите создать",
        "placeholder.parentOffline": "Родительская сессия недоступна; отправка невозможна, но вы можете остановить выполнение",
        "placeholder.steerQueue": "Cmd/Ctrl+Enter отправляет все сообщения из очереди",
        "placeholder.unavailable": "Сессия недоступна",
        "placeholder.workspace": "Выберите рабочую область, чтобы начать",
        "queue.cancelEdit": "Отменить редактирование",
        "queue.count": "{n} сообщений в очереди",
        "queue.edit": "Изменить сообщение в очереди",
        "queue.edit.unsupported": "Содержит нетекстовый контент; редактирование пока не поддерживается",
        "queue.editFailed": "Не удалось изменить: сообщение, возможно, уже начало отправляться.",
        "queue.remove": "Удалить сообщение из очереди",
        "queue.removeFailed": "Не удалось удалить: сообщение, возможно, уже начало отправляться.",
        "queue.save": "Сохранить сообщение из очереди",
        "queue.steer": "Отправить сообщение из очереди",
        "queue.steer.unavailable": "Отправка доступна только пока агент выполняется",
        "queue.steerFailed": "Не удалось отправить. Попробуйте снова.",
        "row.failed": "Не удалось",
        "row.running": "Выполняется",
        "row.stopped": "Остановлено",
        "session.hierarchy": "Иерархия сессии",
        "settings.enter.description": "Только при занятости; Cmd/Ctrl+Enter использует другое поведение",
        "settings.enter.queue": "В очередь",
        "settings.enter.steer": "Отправить",
        "settings.enter.title": "Поведение Enter при занятости",
        "stats.cacheHit": "Попадание в кэш {percent}%",
        "stats.counts": "{turns} ходов · {steps} шагов",
        "stats.llm": "LLM {duration}",
        "stats.tokens": "Ввод {input} ток · Вывод {output} ток",
        "stats.tokensPerSecond": "{throughput} ток/с",
        "stats.toolCall": "Вызов инструмента {duration}",
        "stats.ttftAverage": "TTFT в среднем {duration}",
        "terminal.collapseAria": "Свернуть вывод",
        "terminal.done": "Готово",
        "terminal.exitCode": "код выхода {code}",
        "terminal.expandAria": "Развернуть оставшиеся {n} строк вывода",
        "terminal.expandRest": "… ещё {n} строк",
        "terminal.failed": "Не удалось",
        "terminal.noOutput": "Нет вывода",
        "terminal.running": "Выполняется",
        "terminal.signal": "сигнал {signal}",
        "todo.completed": "Выполнено: {done}/{total}",
        "todo.progress.active": "{active} в работе",
        "todo.progress.done": "{done} выполнено",
        "todo.progress.pending": "{pending} ожидает",
        "todo.rowTitle": "Обновить список задач",
        "todo.title": "Задачи",
        "view.chat": "Чат"
      },
      "permission": {
        "confirm.acknowledge": "Я понимаю риски и хочу продолжить",
        "confirm.cancel": "Отмена",
        "confirm.description": "Полный доступ позволяет новым сессиям сократить шаги подтверждения и выполнять больше действий напрямую, включая чувствительные операции, изменения файлов и внешние команды. Используйте его, только если доверяете последующим задачам.",
        "confirm.enable": "Включить полный доступ",
        "confirm.title": "Включить полный доступ?",
        "description": "Выберите режим разрешений по умолчанию для новых сессий",
        "loading": "Загрузка",
        "title": "Разрешения",
        "unavailable": "Недоступно"
      },
      "settings.models": {
        "add": "Добавить провайдера",
        "addModel": "Добавить модель",
        "advancedHint": "Остальные поля находятся в settings.yaml; редактируйте тот раздел напрямую.",
        "apply": "Применить",
        "applying": "Применение…",
        "baseUrl": "Базовый URL",
        "baseUrlDefault": "По умолчанию провайдера",
        "cancel": "Отмена",
        "close": "Закрыть",
        "conflict": "Кто-то ещё изменил эти настройки, пока карточка была открыта. Закройте её и откройте снова, чтобы редактировать актуальные значения.",
        "contextWindow": "Окно контекста",
        "contextWindowPlaceholder": "Использует значение провайдера по умолчанию",
        "create": "Создать провайдера",
        "creating": "Создание…",
        "credentialConfigured": "API-ключ настроен",
        "credentialMissing": "API-ключ отсутствует",
        "customAdd": "Добавить своего провайдера",
        "customApi": "API-протокол",
        "customApiUnset": "Не выбран",
        "customDisplayName": "Отображаемое имя",
        "customNeedsBaseUrl": "Своему провайдеру нужен базовый URL.",
        "customNeedsModels": "Своему провайдеру нужна хотя бы одна модель.",
        "customRoute": "ID провайдера",
        "customRouteHint": "Идентификатор в нижнем регистре, начинается с буквы, уникально именует провайдера в запросах и как имя его учётных данных.",
        "customRouteInvalid": "Начните со строчной буквы; далее строчные буквы, цифры и дефисы.",
        "customRouteTaken": "Этот ID уже использует другой провайдер.",
        "customTag": "Свой",
        "customTitle": "Свой провайдер",
        "customized": "Изменённые настройки",
        "deleteConfirm": "Удалить {provider}",
        "deleteDescription": "Удаление {provider} удалит его конфигурацию. Используемые им учётные данные управляются отдельно и будут сохранены.",
        "deleteDescriptionWithCredential": "Удаление {provider} удалит его конфигурацию и сохранённый API-ключ.",
        "deleteTitle": "Удалить {provider}?",
        "deleting": "Удаление {provider}…",
        "edit": "Изменить",
        "editProvider": "Изменить {provider}",
        "fetchAdopt": "Добавить выбранные",
        "fetchDescription": "Это модели, доступные у этого провайдера. Выберите, какие добавить.",
        "fetchDeselectAll": "Снять выбор",
        "fetchEmpty": "Провайдер не перечислил моделей. Добавьте их вручную.",
        "fetchModels": "Получить доступные модели",
        "fetchNeedsBaseUrl": "Сначала введите базовый URL, затем получите список.",
        "fetchSelectAll": "Выбрать все",
        "fetchTitle": "Выберите модели для добавления",
        "fetching": "Запрос к провайдеру…",
        "intro": "Введите API-ключи, чтобы использовать модели следующих провайдеров.",
        "keyBlank": "Введите API-ключ или оставьте поле пустым, чтобы сохранить текущий.",
        "keyBlankNew": "Введите API-ключ или оставьте поле пустым, если провайдер использует другой способ аутентификации.",
        "keyEnvLocked": "Предоставлено средой запуска (только чтение)",
        "keyIllegalCharacters": "API-ключ имеет недопустимый формат. Проверьте его.",
        "keyInput": "API-ключ",
        "keyPlaceholder": "Введите ваш API-ключ",
        "keyPlaceholderNative": "Введите API-ключ или оставьте пустым для аутентификации через окружение",
        "keyRequired": "Введите API-ключ, чтобы продолжить.",
        "keyStored": "Настроен — введите новое значение для замены",
        "loadFailed": "Не удалось загрузить каталог провайдеров",
        "maxTokens": "Макс. выходных токенов",
        "maxTokensPlaceholder": "Использует значение провайдера по умолчанию",
        "model": "Модель",
        "modelAdvanced": "Лимиты",
        "modelCapacityInvalid": "Лимит должен быть числом, при желании с суффиксом K или M.",
        "modelContextInvalid": "Окно контекста должно быть положительным числом, например 131072, 256K или 1M.",
        "modelContextWindow": "Окно контекста",
        "modelDuplicate": "Каждый ID модели может встречаться один раз.",
        "modelId": "ID модели",
        "modelIdDuplicate": "ID модели должен быть уникальным.",
        "modelIdRequired": "Требуется ID модели.",
        "modelMaxTokens": "Макс. выходных токенов",
        "modelMaxTokensInvalid": "Макс. выходных токенов должно быть положительным числом, например 8192, 64K или 1M.",
        "modelName": "Отображаемое имя",
        "modelNameInvalid": "Отображаемое имя не может быть пустым.",
        "modelNamePlaceholder": "Использует ID модели, если пусто",
        "models": "Модели",
        "modelsCustomized": "Изменённый каталог моделей",
        "modelsEmpty": "Ни одна модель не будет показана в селекторе. Не перечисленные ID всё ещё можно отправлять напрямую.",
        "modelsInherited": "Используются настройки адаптера по умолчанию",
        "nav": "Модели",
        "onboardingDescription": "Настройте официального провайдера DeepSeek, чтобы начать работу.",
        "onboardingLater": "Настроить позже",
        "onboardingSave": "Сохранить и продолжить",
        "onboardingSaving": "Сохранение…",
        "onboardingTitle": "Добавьте API-ключ, чтобы начать",
        "provider": "Провайдер",
        "readOnly": "Документ настроек доступен только для чтения в этой установке.",
        "remove": "Удалить",
        "removeModel": "Удалить модель",
        "removeProvider": "Удалить {provider}",
        "resetModels": "Вернуть по умолчанию",
        "retry": "Повторить",
        "savedProvider": "Сохранено: {provider}.",
        "title": "Модели",
        "welcomeError": "Не удалось сохранить подтверждение. Попробуйте снова."
      },
      "settings.pluginInventory": {
        "active": "Подключено",
        "catalog": "Список плагинов",
        "configuration": "Конфигурация",
        "cordis": "Статус Cordis",
        "disabledTag": "Отключено",
        "empty": "Нет доступных плагинов.",
        "emptySearch": "Нет подходящих плагинов.",
        "enabledTag": "Включено",
        "error": "Плагины временно недоступны.",
        "failed": "Не удалось подключить",
        "loading": "Чтение плагинов…",
        "loadingPhase": "Загрузка",
        "pending": "Ожидание зависимостей",
        "retry": "Повторить",
        "search": "Поиск плагинов",
        "tab": "Список плагинов",
        "unloading": "Отключение",
        "unobserved": "Не подключено"
      },
      "settings.plugins": {
        "agentLoopDescription": "Как агент распределяет вызовы инструментов.",
        "agentLoopMaxParallel": "Параллельные вызовы инструментов",
        "agentLoopMaxParallelHint": "Верхний предел параллельно-безопасных вызовов, выполняющихся одновременно в одном шаге.",
        "agentLoopTitle": "Цикл агента",
        "bashDescription": "Ограничения для каждой команды, которую выполняет агент.",
        "bashMaxOutputBytes": "Лимит вывода на поток (байты)",
        "bashMaxOutputBytesHint": "Вывод сверх лимита сохраняется во временный файл, а не теряется.",
        "bashTimeoutMs": "Таймаут команды (мс)",
        "bashTimeoutMsHint": "Сколько может выполняться команда до её завершения.",
        "bashTitle": "Терминал",
        "collapse": "Скрыть настройки",
        "configurableTab": "Конфигурация плагинов",
        "discard": "Отменить",
        "empty": "Эта установка не предоставляет настроек плагинов.",
        "expand": "Показать настройки",
        "intro": "Настройка и просмотр плагинов, установленных в этой установке.",
        "invalidNumber": "Введите число или оставьте пустым, чтобы использовать значение по умолчанию.",
        "nav": "Плагины",
        "overridden": "Переопределено",
        "readOnly": "Эта установка хранит настройки только для чтения.",
        "reset": "Сбросить на значение по умолчанию",
        "save": "Сохранить",
        "saveFailed": "Установка не приняла эти значения; они оставлены для исправления.",
        "saving": "Сохранение…",
        "tabs": "Разделы плагинов",
        "title": "Плагины",
        "unsaved": "Не сохранено",
        "webSearchApiKey": "API-ключ",
        "webSearchApiKeyHint": "Хранится вне файла настроек. Оставьте пустым, чтобы сохранить текущий ключ.",
        "webSearchApiKeySet": "Ключ настроен.",
        "webSearchApiKeyUnset": "Ключ не настроен; поиск недоступен, пока его нет.",
        "webSearchBaseUrl": "Конечная точка",
        "webSearchBaseUrlHint": "Оставьте пустым, чтобы использовать значение провайдера по умолчанию.",
        "webSearchDescription": "Поисковый провайдер DeepSeek.",
        "webSearchMaxUses": "Макс. поисков за запрос",
        "webSearchMaxUsesHint": "Сколько раз один запрос может выполнять поиск, прежде чем ответить.",
        "webSearchTitle": "Веб-поиск"
      },
      "settings.theme": {
        "appearance.dark": "Тёмная",
        "appearance.light": "Светлая",
        "appearance.system": "Системная",
        "appearance.title": "Оформление"
      },
      "slash.menu": {
        "command": "Команды",
        "loading": "Загрузка…",
        "skill": "Навыки",
        "subagent": "Субагенты",
        "suggestions.aria": "Подсказки команд"
      }
    };

    exports.name = "dsh-locale-ru";
    exports.inject = ["locale"];

    exports.apply = function (ctx) {
      var locale = ctx.locale;
      if (!locale) return;

      // Регистрируем русские словари (жизненный цикл привязан к плагину).
      ctx.effect(function () {
        var disposers = [];
        Object.keys(RU).forEach(function (ns) {
          try {
            disposers.push(locale.register(ns, { ru: RU[ns] }));
          } catch (e) { /* namespace already registered — ignore */ }
        });
        return function () {
          disposers.forEach(function (d) { if (d) d(); });
        };
      });

      // 1. Добавляем "ru" в список языков (выпадающий список + валидация setLocale).
      var locales = locale.snapshot && locale.snapshot.locales ? locale.snapshot.locales : [];
      var hasRu = locales.some(function (l) { return l.id === "ru"; });
      if (!hasRu) {
        locale.snapshot = Object.freeze(Object.assign({}, locale.snapshot, {
          locales: [{ id: "ru", label: "Русский" }].concat(locales)
        }));
      }

      // 2. Схема настроек хоста принимает только zh/en — держим выбор локально.
      locale.adopt = function () { return undefined; };
      var origSetLocale = locale.setLocale.bind(locale);
      locale.setLocale = function (id) {
        if (id === "ru") {
          try { localStorage.setItem("dsh-locale-ru:pref", "ru"); } catch (e) {}
          if (locale.snapshot.active !== "ru") locale.publish("ru", true);
          return;
        }
        try { localStorage.removeItem("dsh-locale-ru:pref"); } catch (e) {}
        origSetLocale(id);
      };

      // 3. Включаем русский, если браузер предпочитает его или выбор сохранён.
      var wantsRu = false;
      var savedRu = false;
      try {
        savedRu = localStorage.getItem("dsh-locale-ru:pref") === "ru";
        var tags = (navigator.languages || [navigator.language]).map(String);
        wantsRu = tags.some(function (t) { return t && t.toLowerCase().indexOf("ru") === 0; });
      } catch (e) {}
      if (savedRu || wantsRu) {
        locale.publish("ru", locale.snapshot.active !== "ru");
      } else {
        locale.publish(locale.snapshot.active, false);
      }
    };

    return module.exports;
  }
});
