// dsh-locale-ru — русский интерфейс для DeepSeek Harness (dsh).
//
// Клиентская половина плагина. Работает только через публичный API сервиса
// локали `@deepseek-ai/dsh-client-locale` (ctx.locale):
//
//   ctx.locale.addLanguage({ id: 'ru', label: 'Русский', fallback: 'en' })
//   ctx.locale.register(namespace, 'ru', { ключ: 'перевод' })
//
// Отдельный код активации не нужен: язык применяется автоматически, если он
// выбран в настройках (locale.preference в $DSH_HOME/settings.yaml) или если
// браузер предпочитает русский. Недостающие ключи разрешаются по цепочке
// ru → en, поэтому частичный словарь безопасен.
window.__ModuleLoader__.load({
  id: '@dsh-local/locale-ru',
  factory: function (require) {
    var module = { exports: {} }
    var exports = module.exports

    /** Регистрируемый язык, его подпись и язык фолбэка (встроен в dsh). */
    var LOCALE_ID = 'ru'
    var LOCALE_LABEL = 'Русский'
    var FALLBACK_ID = 'en'

    /** Ключ, которым прежние версии плагина хранили выбор языка в браузере. */
    var LEGACY_PREF_KEY = 'dsh-locale-ru:pref'

    // Русские словари: namespace -> { ключ: перевод }. Набор ключей совпадает с
    // английскими словарями dsh; namespace и ключ — это контракт поиска.

    var RU = {
      "approval": {
        "allowOnce": "Разрешить один раз",
        "detail.aria": "Подробности одобрения",
        "escalation": "Инструмент {toolName} запрашивает привилегированное выполнение",
        "reject": "Отклонить",
        "waiting": "Ожидание одобрения"
      },
      "chat": {
        "chat.deepDiving": "Погружается в задачу…",
        "chat.loadError": "Не удалось загрузить историю: {message} ({code})",
        "chat.loadOlder": "Загрузить ранее",
        "chat.loadingHistory": "Загрузка истории…",
        "chat.toBottom": "Вниз",
        "chat.turnNavigation.jump": "Перейти к шагу {turn}",
        "chat.turnNavigation.jumpLoad": "Загрузить и перейти к шагу {turn}",
        "chat.turnNavigation.label": "Навигация по шагам",
        "chat.turnNavigation.turn": "Шаг {turn}",
        "clock.md": "{m}/{d}",
        "clock.ymd": "{y}-{m}-{d}",
        "command.done": "Завершено",
        "command.failed": "Не удалось выполнить команду",
        "command.running": "Выполняется…",
        "command.title": "Команда",
        "duration.compactMinutes": "{minutes} мин {seconds} с",
        "duration.compactSeconds": "{seconds} с",
        "duration.milliseconds": "{milliseconds} мс",
        "duration.minutes": "{minutes} мин {seconds} с",
        "duration.seconds": "{seconds} с",
        "fileOpen.title": "Не удалось открыть файл",
        "fileOpen.unknown": "Не удалось открыть этот файл",
        "json.truncated": "… обрезано, всего символов: {total}",
        "message.branch": "Ответвить в новый диалог",
        "message.branchUnavailable": "Доступно только для последнего сообщения завершённого шага",
        "message.compaction": "Контекст сжат",
        "message.compaction.commandTitle": "compact",
        "message.compaction.completed": "Сжато элементов истории: {items} (~{tokens} токенов)",
        "message.compaction.expand": "Показать сводку сжатия",
        "message.compaction.running": "Сжатие контекста…",
        "message.compaction.unavailable": "Сводка сжатия недоступна",
        "message.context.catalog.more": "… ещё {count}",
        "message.context.catalog.replaced": "Каталог замен",
        "message.context.instructions.added": "добавлено",
        "message.context.instructions.loaded": "загружено",
        "message.context.instructions.removed": "удалено",
        "message.context.instructions.updated": "обновлено",
        "message.context.recall.counts": "сохранено {retained} · пропущено {omitted}",
        "message.context.recall.truncated": "обрезано",
        "message.context.relay.from": "Из сессии {session}",
        "message.context.snapshot.supersedes": "Заменяет предыдущие снимки",
        "message.contextInjection": "Внедрение контекста",
        "message.contextRecall": "Из памяти сессии",
        "message.extraBlock": "Дополнительный блок содержимого",
        "message.failure.auth": "API-ключ недействителен",
        "message.maxTokens": "Достигнут лимит выходных токенов",
        "message.maxTokens.hint": "Ответ был обрезан; предыдущий вывод сохранён в диалоге. Отправьте «continue», чтобы модель продолжила.",
        "message.ranFor": "Выполнялось {duration}",
        "message.referenceSeparator": ", ",
        "message.referenceSummary": "Ссылка на сессию · {labels}",
        "message.retry.active": "Повтор запроса к модели",
        "message.retry.cancelled": "Повтор запроса к модели отменён",
        "message.retry.delay": "Задержка повтора: ",
        "message.retry.failure": "Причина сбоя: ",
        "message.retry.scheduled": "Ожидание повтора запроса к модели",
        "message.retry.started": "Запрос к модели повторён",
        "message.retry.status": "{label} ({retry}/{maximum}) · {seconds} с",
        "message.stopped": "Остановлено",
        "message.systemPrompt": "Системный промпт",
        "message.systemPromptUpdate": "Обновление системного промпта",
        "message.think": "Рассуждение",
        "message.tokensPerSecond": "{tps} ток./с",
        "message.turnError": "Этот шаг завершился ошибкой",
        "message.turnProcess.messages.one": "{count} сообщение",
        "message.turnProcess.messages.other": "{count} сообщений",
        "message.turnProcess.separator": " · ",
        "message.turnProcess.subagents.one": "{count} субагент",
        "message.turnProcess.subagents.other": "{count} субагентов",
        "message.turnProcess.thoughtForAWhile": "Размышлял некоторое время",
        "message.turnProcess.toolCalls.one": "{count} вызов инструмента",
        "message.turnProcess.toolCalls.other": "{count} вызовов инструментов",
        "message.turnTime.duration": "Общее время выполнения",
        "message.turnTime.speed": "Токенов в секунду (TPS)",
        "message.turnTime.title": "Время шага и скорость",
        "message.turnTime.ttft": "Время до первого токена (TTFT)",
        "message.turnUsage.cacheHit": "Попадание в кэш",
        "message.turnUsage.cacheRead": "Ввод из кэша",
        "message.turnUsage.cacheWrite": "Запись в кэш",
        "message.turnUsage.consumed": "Использовано {total}",
        "message.turnUsage.count": "{count} ток.",
        "message.turnUsage.input": "Ввод без кэша",
        "message.turnUsage.model": "Провайдер / модель",
        "message.turnUsage.output": "Вывод",
        "message.turnUsage.reasoning": " ({tokens} на рассуждения)",
        "message.turnUsage.title": "Использование за шаг",
        "message.unknownBlock": "Неизвестный блок содержимого",
        "message.unknownSurface": "Неизвестное событие интерфейса: {type}",
        "number.groupSeparator": ",",
        "row.failed": "Не удалось",
        "row.running": "Выполняется",
        "settings.transcript.compact": "Сжатый",
        "settings.transcript.description": "Управляет отображением процесса в завершённых шагах",
        "settings.transcript.normal": "Обычный",
        "settings.transcript.title": "Отображение диалога",
        "stats.cacheHit": "Попаданий в кэш: {percent}%",
        "stats.counts": "{turns} шагов {steps} этапов",
        "stats.dialog.llmTime": "Время LLM",
        "stats.dialog.speed": "Токенов в секунду (TPS)",
        "stats.dialog.title": "Статистика сессии",
        "stats.dialog.toolTime": "Время инструментов",
        "stats.dialog.ttft": "Среднее время до первого токена (TTFT)",
        "stats.dialog.usageTitle": "Использование токенов",
        "view.chat": "Чат"
      },
      "command": {
        "description.compact": "Сжать старую историю диалога",
        "description.export": "Скачать журнал этой сессии ZIP-архивом",
        "description.feedback": "оставить отзыв об этой сессии",
        "description.goal": "задать или посмотреть цель длительной задачи",
        "description.permission": "Переключить пресет разрешений (режим песочницы + политика одобрений)",
        "description.plan": "Войти в режим планирования или выйти из него",
        "listbox.aria": "/{command} совпадений",
        "notice.attachmentsUnsupported": "/{command} не принимает вложения; сначала удалите их",
        "overlay.aria": "Параметры /{command}",
        "search.aria": "Фильтровать параметры",
        "search.placeholder": "Поиск…",
        "status.applying": "Применение…",
        "status.empty": "Нет параметров",
        "status.loading": "Загрузка параметров…"
      },
      "common": {
        "back": "Назад",
        "brand.localBuild": "Локальная сборка DSH",
        "cancel": "Отмена",
        "close": "Закрыть",
        "collapse": "Свернуть",
        "copied": "Скопировано",
        "copy": "Копировать",
        "copy.compactJson": "Копировать сжатый JSON",
        "copy.failed": "Не удалось скопировать",
        "copy.json": "Копировать JSON",
        "copy.optionsHint": "{action}; правый щелчок — варианты копирования",
        "copy.path": "Копировать путь свойства",
        "copy.prettyJson": "Копировать форматированный JSON",
        "copy.value": "Копировать значение",
        "delete": "Удалить",
        "edit": "Изменить",
        "expand": "Развернуть",
        "json.collapseNode": "Свернуть узел JSON",
        "json.expandNode": "Развернуть узел JSON",
        "json.label": "JSON",
        "load.failed": "Не удалось загрузить",
        "loading": "Загрузка…",
        "markdown.footnotes": "Сноски",
        "markdown.truncatedCharacters": "… обрезано после {total} символов",
        "more": "Ещё",
        "next": "Далее",
        "none": "Нет",
        "number.million": "{value} млн",
        "number.thousand": "{value} тыс.",
        "ok": "ОК",
        "previous": "Назад",
        "retry": "Повторить",
        "save": "Сохранить",
        "search": "Поиск",
        "skip": "Пропустить",
        "submit": "Отправить",
        "submitting": "Отправка…",
        "truncated": "Обрезано",
        "unknown": "Неизвестно"
      },
      "conversation": {
        "access.confirm.acknowledge": "Я понимаю риски и хочу продолжить",
        "access.confirm.cancel": "Отмена",
        "access.confirm.description": "Полный доступ сокращает шаги подтверждения и позволяет агенту выполнять больше действий напрямую, включая чувствительные операции, изменения файлов и внешние команды. Используйте его, только если доверяете текущей задаче.",
        "access.confirm.enable": "Включить полный доступ",
        "access.confirm.title": "Включить полный доступ?",
        "access.preset.fullAccess": "Полный доступ",
        "access.preset.readOnly": "Только чтение",
        "access.preset.workspaceWrite": "Запись в рабочую область",
        "ask.answered": "Отвечено: {answered}/{total}",
        "ask.cancelled": "отменено",
        "ask.cancelledDetail": "Набор вопросов был отменён до отправки ответов.",
        "ask.interrupted": "прервано",
        "ask.interruptedDetail": "Набор вопросов был прерван до отправки ответов.",
        "ask.rowTitle": "Задать вопрос",
        "ask.skipped": "Без ответа",
        "ask.waiting": "ожидание",
        "attachment.dropBlocked": "Сейчас нельзя добавлять файлы и изображения",
        "attachment.dropDesc": "Лимит изображений: до {count} шт., по {size} каждое",
        "attachment.dropTitle": "Перетащите сюда файлы или изображения",
        "attachment.pending": "Ожидающие вложения",
        "attachment.scrollLeft": "Прокрутить вложения влево",
        "attachment.scrollRight": "Прокрутить вложения вправо",
        "bash.failed": "Не удалось",
        "bash.running": "Выполняется",
        "bash.stopped": "Остановлено",
        "command.attachmentsUnsupported": "/{command} не принимает вложения; сначала удалите их",
        "context.aria": "Использовано {percent} контекста",
        "context.messages": "Сообщения",
        "context.system": "Системный промпт",
        "context.tools": "Определения инструментов",
        "context.used": "контекста использовано",
        "details.running": "Выполняется…",
        "diff.collapseAria": "Свернуть дифф",
        "diff.expandAria": "Развернуть ещё {count} строк диффа",
        "diff.expandRest": "… ещё {count} строк",
        "diff.files.one": "{count} файл",
        "diff.files.other": "{count} файлов",
        "file.attach": "Добавить вложение",
        "file.label": "Файл",
        "file.notStaged": "Файл ещё не загружен; добавьте его снова и повторите",
        "file.pending": "Ожидающие файлы",
        "file.remove": "Удалить файл {name}",
        "file.retry": "Повторить загрузку {name}",
        "file.sessionUnavailable": "Сессия недоступна; загрузка файлов невозможна",
        "file.stillUploading": "Файлы ещё загружаются; отправьте после завершения",
        "file.uploadFailed": "Не удалось загрузить; нажмите, чтобы повторить",
        "file.uploading": "Загрузка…",
        "hero.chooseWorkspace": "Выбрать рабочую область",
        "hero.headline": "В неизведанное",
        "hero.preview": "Предпросмотр",
        "hint.goal": "опишите цель для длительной задачи",
        "hint.goal.active": "цель активна — изменить / пауза / возобновить / очистить",
        "hint.plan": "опишите задачу, чтобы построить план",
        "image.closePreview": "Закрыть предпросмотр исходного изображения",
        "image.dimensionTooLarge": "Стороны изображения должны быть не больше {size}px; уменьшите его и попробуйте снова",
        "image.fileTooLarge": "Каждое изображение должно быть меньше {size}",
        "image.label": "Изображение",
        "image.loadFailed": "Не удалось загрузить изображение; нажмите, чтобы повторить",
        "image.loading": "Загрузка изображения…",
        "image.modelUnsupported": "Текущая модель не поддерживает изображения; переключитесь на модель, которая их поддерживает",
        "image.openOriginal": "Открыть оригинал",
        "image.openOriginalLabel": "{label}, нажмите, чтобы открыть оригинал",
        "image.original": "Исходное изображение",
        "image.pending": "Ожидают отправки",
        "image.preview": "Предпросмотр исходного изображения",
        "image.remove": "Удалить изображение {name}",
        "image.sendFailed": "Не удалось отправить изображения ({reason}); добавьте их снова и повторите",
        "image.tooMany": "Сообщение может содержать до {count} изображений",
        "image.tooManyPixels": "Разрешение изображения слишком высокое; сожмите его и попробуйте снова",
        "image.totalTooLarge": "Изображения суммарно превышают {size}; удалите часть и попробуйте снова",
        "image.unsupportedType": "Поддерживаются только изображения PNG, JPG, WebP и GIF",
        "input.accessMode": "Режим доступа, текущий: {name}",
        "input.commands": "Команды",
        "input.send": "Отправить сообщение",
        "input.send.queue": "Поставить сообщение в очередь",
        "input.send.steer": "Вмешаться в выполнение",
        "input.stop": "Остановить генерацию",
        "placeholder.default": "Напишите сообщение или задачу; / — команды, @ — файлы и сессии",
        "placeholder.hero": "Опишите, что хотите создать; / — команды, @ — файлы и сессии",
        "placeholder.parentOffline": "Родительская сессия недоступна; отправка невозможна, но вы можете остановить выполнение",
        "placeholder.plan": "опишите задачу, чтобы построить план",
        "placeholder.steerQueue": "Cmd/Ctrl+Enter отправляет все сообщения из очереди",
        "placeholder.unavailable": "Сессия недоступна",
        "placeholder.workspace": "Выберите рабочую область, чтобы начать",
        "queue.cancelEdit": "Отменить редактирование",
        "queue.count": "{n} сообщений в очереди",
        "queue.edit": "Изменить сообщение в очереди",
        "queue.edit.unsupported": "Содержит нетекстовый контент; редактирование пока не поддерживается",
        "queue.editFailed": "Не удалось изменить: сообщение, возможно, уже начало отправляться.",
        "queue.file": "Файл в очереди: {name}",
        "queue.image": "Изображение в очереди",
        "queue.remove": "Удалить сообщение из очереди",
        "queue.removeFailed": "Не удалось удалить: сообщение, возможно, уже начало отправляться.",
        "queue.save": "Сохранить сообщение из очереди",
        "queue.sending": "Отправка…",
        "queue.steer": "Отправить сообщение из очереди",
        "queue.steer.unavailable": "Отправка доступна только пока агент выполняется",
        "queue.steerFailed": "Не удалось отправить. Попробуйте снова.",
        "read.collapseAria": "Свернуть содержимое",
        "read.expandAria": "Развернуть ещё {count} строк",
        "read.expandRest": "… ещё {count} строк",
        "read.window": "Показано {shown} из {total} строк",
        "row.failed": "Не удалось",
        "row.input": "ВХОД",
        "row.inspect": "Просмотр",
        "row.output": "ВЫХОД",
        "row.running": "Выполняется",
        "row.stopped": "Остановлено",
        "search.collapseAria": "Свернуть результаты",
        "search.expandAria": "Развернуть ещё {count} строк результатов",
        "search.expandRest": "… ещё {count} строк",
        "search.matches": "совпадений: {shown} · файлов: {files}",
        "search.matches.truncated": "Показано {shown} из {total} совпадений · файлов: {files}",
        "search.noResults": "Ничего не найдено",
        "search.paths": "путей: {shown}",
        "search.paths.truncated": "Показано {shown} из {total} путей",
        "session.hierarchy": "Иерархия сессии",
        "settings.enter.description": "Что делают Enter и кнопка отправки, пока агент работает; Cmd/Ctrl+Enter использует другое поведение",
        "settings.enter.queue": "В очередь",
        "settings.enter.steer": "Отправить",
        "settings.enter.title": "Поведение отправки при занятости",
        "terminal.collapseAria": "Свернуть вывод",
        "terminal.done": "Готово",
        "terminal.exitCode": "код выхода {code}",
        "terminal.expandAria": "Развернуть оставшиеся {n} строк вывода",
        "terminal.expandRest": "… ещё {n} строк",
        "terminal.failed": "Не удалось",
        "terminal.noOutput": "Нет вывода",
        "terminal.running": "Выполняется",
        "terminal.sendInput": "(отправить ввод)",
        "terminal.session": "Терминал {sessionId}",
        "terminal.signal": "сигнал {signal}",
        "todo.completed": "Выполнено: {done}/{total}",
        "todo.progress.active": "{active} в работе",
        "todo.progress.done": "{done} выполнено",
        "todo.progress.pending": "{pending} ожидает",
        "todo.rowTitle": "Обновить список задач",
        "todo.title": "Задачи",
        "tool.title.bash": "Bash",
        "tool.title.code": "Код",
        "tool.title.edit": "Изменить",
        "tool.title.generic": "Вызов инструмента",
        "tool.title.glob": "Glob",
        "tool.title.grep": "Grep",
        "tool.title.inspect": "Просмотр",
        "tool.title.pwsh": "Pwsh",
        "tool.title.read": "Чтение",
        "tool.title.readImage": "Чтение изображения",
        "tool.title.removeCordis": "Удалить плагин Cordis",
        "tool.title.runCordis": "Запустить плагин Cordis",
        "tool.title.search": "Поиск",
        "tool.title.stopCordis": "Остановить плагин Cordis",
        "tool.title.webFetch": "Загрузка",
        "tool.title.webSearch": "Поиск",
        "tool.title.write": "Запись",
        "web.contentTruncated": "Содержимое обрезано",
        "web.http": "HTTP",
        "web.noResults": "Ничего не найдено",
        "web.sourcesTruncated": "Список источников обрезан"
      },
      "cordis": {
        "a11y.defining": "Определение плагина",
        "a11y.failed": "Не удалось определить",
        "a11y.stopped": "Определение прервано",
        "action.approve": "Разрешить",
        "action.approveOnce": "Разрешить только эту версию",
        "action.approvePlugin": "Разрешить будущие версии этого плагина",
        "action.decline": "Отклонить",
        "action.inspect": "Просмотр",
        "action.remove": "Удалить",
        "action.retry": "Повторить",
        "action.rollback": "Откатить",
        "action.run": "Запустить",
        "action.stop": "Остановить",
        "body.clientCode": "Клиент",
        "body.copied": "Скопировано",
        "body.copy": "Копировать",
        "body.hostCode": "Хост",
        "body.output": "Результат",
        "body.source": "Исходный код плагина",
        "panel.approvals.aria": "Разрешения Cordis",
        "panel.current": "Текущий: {packageId}",
        "panel.empty": "Плагины ещё не определены",
        "panel.group.current": "Эта сессия",
        "panel.group.others": "Другие сессии",
        "panel.hint": "Элементы управления запуском находятся на панели Cordis над «Настройками»",
        "panel.loading": "Чтение…",
        "panel.next": "Далее: {packageId}",
        "panel.plugins.aria": "Плагины Cordis",
        "panel.readFailed": "Не удалось прочитать список плагинов: {message}",
        "panel.runningCount": "Запущено: {count}",
        "panel.title": "Плагины Cordis",
        "panel.trigger": "Плагин Cordis",
        "panel.version": "Версия",
        "purpose.missing": "(назначение не указано)",
        "render.failedAbdicated": "Не удалось отобразить {slot}; восстановлен интерфейс по умолчанию:",
        "render.failedHeld": "Не удалось отобразить {slot}:",
        "row.defineTitle": "Зарегистрировать плагин Cordis",
        "row.removeTitle": "Удалить плагин Cordis",
        "row.runTitle": "Запустить плагин Cordis",
        "row.stopTitle": "Остановить плагин Cordis",
        "row.updateTitle": "Обновить плагин Cordis",
        "run.removed": "Этот пакет больше не существует",
        "run.superseded": "Ниже доступна карточка более нового запуска",
        "status.awaitingApproval": "Ожидает одобрения",
        "status.clientPending": "Клиент готов к активации",
        "status.failed": "Запуск не удался",
        "status.idle": "Готов",
        "status.removed": "Удалено",
        "status.running": "Выполняется",
        "status.superseded": "Доступен более новый запуск"
      },
      "deliverables": {
        "presented.action": "Открыть",
        "presented.all": "Все файлы ({count})",
        "presented.collapse": "Свернуть",
        "presented.collapseAria": "Свернуть созданные файлы",
        "presented.defaultApp": "Открыть в приложении по умолчанию",
        "presented.directory": "Открыть папку с файлом",
        "presented.directoryError": "Не удалось открыть папку с файлом. Попробуйте ещё раз.",
        "presented.directoryOpened": "Запрошено открытие папки с файлом",
        "presented.directoryOpening": "Открытие папки с файлом…",
        "presented.error": "Не удалось открыть. Нажмите, чтобы повторить.",
        "presented.expandAria": "Показать все созданные файлы ({count})",
        "presented.explorer": "Показать в Проводнике",
        "presented.file": "Файл",
        "presented.finder": "Показать в Finder",
        "presented.hostError": "Не удалось получить сведения о рабочем столе хоста",
        "presented.more": "Другие действия с файлом {name}",
        "presented.nativeUnavailable": "У этого файла нет доступного пути на хосте. Откройте предпросмотр в боковой панели.",
        "presented.open": "Открыть {name} в приложении по умолчанию",
        "presented.opened": "Открыто в приложении по умолчанию",
        "presented.opening": "Открытие…",
        "presented.preview": "Предпросмотр в боковой панели",
        "presented.previewButton": "Открыть {name} в боковой панели",
        "presented.previewCard": "Предпросмотр {name} в боковой панели",
        "presented.retry": "Повторить",
        "presented.revealError": "Не удалось показать в файловом менеджере. Попробуйте ещё раз.",
        "presented.revealed": "Запрошен показ в файловом менеджере",
        "presented.revealing": "Показ в файловом менеджере…",
        "presented.unavailable": "На этом хосте нет рабочего стола для открытия файлов и папок",
        "produced.label": "Изменённые файлы",
        "produced.more": "+ {count} файлов",
        "produced.moreOne": "+ 1 файл",
        "produced.open": "Открыть {name}",
        "row.error": "Не удалось передать",
        "row.inspect": "Просмотр вызова",
        "row.ok": "Передано",
        "row.running": "Передача…",
        "row.stopped": "Прервано",
        "row.title": "Созданные файлы"
      },
      "directory-browser": {
        "browser.cancel": "Отмена",
        "browser.create": "Создать",
        "browser.createIn": "Новая папка в «{name}»",
        "browser.editPath": "Изменить путь",
        "browser.folderName": "Имя папки",
        "browser.home": "Домашняя папка",
        "browser.loading": "Загрузка…",
        "browser.newFolder": "Новая папка",
        "browser.open": "Открыть",
        "browser.showHidden": "Показывать скрытые файлы",
        "browser.title": "Выбор папки рабочей области",
        "browser.truncated": "Слишком много папок для показа; показано только начало.",
        "browser.untitledFolder": "Папка без названия"
      },
      "documentHtml": {
        "failed": "Не удалось показать этот документ HTML.",
        "frame": "Предпросмотр документа HTML",
        "loading": "Подготовка предпросмотра HTML…",
        "title": "HTML"
      },
      "documentMarkdown": {
        "code.copied": "Скопировано",
        "code.copy": "Копировать",
        "footnotes": "Сноски",
        "viewer.label": "Markdown"
      },
      "feedback": {
        "action.dislike": "Плохой ответ",
        "action.dislikeActive": "Убрать оценку",
        "action.like": "Хороший ответ",
        "action.likeActive": "Убрать оценку",
        "category.instruction-following": "Понимание и следование инструкциям",
        "category.other": "Другое",
        "category.product-interaction": "Возможности и удобство работы",
        "category.resource-cost": "Расход ресурсов и стоимость",
        "category.security-privacy-permission": "Безопасность, приватность и разрешения",
        "category.service-stability": "Стабильность и скорость",
        "category.task-result": "Результат задачи",
        "dialog.categories": "Категория отзыва",
        "dialog.detail": "Подробности отзыва",
        "dialog.hint": "Добавьте подробности, чтобы помочь нам стать лучше. В отправку войдёт журнал текущего диалога.",
        "dialog.title": "Отправить отзыв",
        "error.conflict": "Этот отзыв был изменён в другом месте; показано актуальное состояние",
        "error.generic": "Не удалось сохранить отзыв",
        "error.load": "Не удалось загрузить отзыв",
        "error.noteTooLarge": "Описание слишком длинное; сократите его и отправьте снова",
        "toast.recorded": "Спасибо за отзыв"
      },
      "goal": {
        "action.cancel": "Отменить изменение",
        "action.clear": "Очистить цель",
        "action.edit": "Изменить цель",
        "action.pause": "Поставить цель на паузу",
        "action.resume": "Возобновить цель",
        "action.save": "Сохранить цель",
        "commandInput.aria": "Ввод команды",
        "objective.aria": "Цель",
        "phase.active": "Активная цель",
        "phase.active.disarmed": "Неактивная цель",
        "phase.blocked": "Заблокированная цель",
        "phase.paused": "Приостановленная цель"
      },
      "job": {
        "count.idle.one": "{count} фоновая задача",
        "count.idle.other": "{count} фоновых задач",
        "count.live.one": "{count} фоновая задача выполняется",
        "count.live.other": "{count} фоновых задач выполняется",
        "duration.hours": "{hours} ч {minutes} мин",
        "duration.minutes": "{minutes} мин {seconds} с",
        "duration.seconds": "{seconds} с",
        "duration.title.done": "Заняло {duration}",
        "duration.title.live": "Выполняется {duration}",
        "list.aria": "Фоновые задачи",
        "status.completed": "завершено",
        "status.failed": "ошибка",
        "status.killed": "отменено",
        "status.running": "выполняется",
        "status.stopping": "останавливается"
      },
      "model": {
        "action.reload": "Перезагрузить",
        "blocked.composer": "Эта модель недоступна — выберите другую, чтобы продолжить",
        "command.description": "Выбрать модель для этого диалога",
        "effort.providerDefault": "По умолчанию",
        "empty.efforts": "Эта модель не предоставляет уровней усилий рассуждения.",
        "empty.models": "Нет доступных моделей.",
        "error.action": "Операция с моделью не удалась: {message}",
        "menu.aria": "Модель и усилия рассуждения",
        "menu.effort": "Усилия",
        "menu.model": "Модель",
        "option.deepseekV4Flash.description": "Быстрая, эффективная и экономичная; подходит для сфокусированных, рутинных и параллельных задач.",
        "option.deepseekV4Pro.description": "Более сильна в агентном кодинге, работе со знаниями и сложных рассуждениях; подходит для сложных задач и задач с высокими требованиями к качеству, но дороже.",
        "option.loadError": "Не удалось загрузить каталог: {message}",
        "status.loading": "Обновление списка моделей…",
        "trigger.aria": "Выбрать модель, текущая: {model}",
        "trigger.ariaEffort": "Выбрать модель, текущая: {model}, усилия рассуждения: {effort}",
        "trigger.fallback": "Выбрать модель",
        "trigger.loading": "Загрузка моделей…",
        "trigger.selectAria": "Выбрать модель",
        "warning.groupLoad": "Не удалось загрузить {name}: {message}"
      },
      "open-in-app": {
        "app.androidstudio": "Android Studio",
        "app.cursor": "Cursor",
        "app.explorer": "File Explorer",
        "app.filemanager": "Files",
        "app.finder": "Finder",
        "app.fork": "Fork",
        "app.ghostty": "Ghostty",
        "app.gitbash": "Git Bash",
        "app.github": "GitHub Desktop",
        "app.gitkraken": "GitKraken",
        "app.gnometerminal": "GNOME Terminal",
        "app.goland": "GoLand",
        "app.intellij": "IntelliJ IDEA",
        "app.iterm": "iTerm2",
        "app.kitty": "kitty",
        "app.konsole": "Konsole",
        "app.phpstorm": "PhpStorm",
        "app.pycharm": "PyCharm",
        "app.rider": "Rider",
        "app.rustrover": "RustRover",
        "app.smartgit": "SmartGit",
        "app.sourcetree": "Sourcetree",
        "app.sublimemerge": "Sublime Merge",
        "app.sublimetext": "Sublime Text",
        "app.terminal": "Terminal",
        "app.tower": "Tower",
        "app.vscode": "VS Code",
        "app.vscodeinsiders": "VS Code Insiders",
        "app.warp": "Warp",
        "app.webstorm": "WebStorm",
        "app.windowsterminal": "Windows Terminal",
        "app.windsurf": "Windsurf",
        "app.xcode": "Xcode",
        "app.zed": "Zed",
        "menu.aria": "Открыть в",
        "menu.toggle": "Выберите приложение, в котором открыть",
        "open.error": "Не удалось открыть",
        "open.title": "Открыть рабочую область в {app}",
        "open.tooltip": "Открыть локально"
      },
      "permission.access": {
        "confirm.acknowledge": "Я понимаю риски и хочу продолжить",
        "confirm.cancel": "Отмена",
        "confirm.description": "Полный доступ сокращает шаги подтверждения и позволяет агенту выполнять больше действий напрямую, включая чувствительные операции, изменения файлов и внешние команды. Используйте его, только если доверяете текущей задаче.",
        "confirm.enable": "Включить полный доступ",
        "confirm.title": "Включить полный доступ?",
        "preset.fullAccess": "Полный доступ",
        "preset.readOnly": "Только чтение",
        "preset.workspaceWrite": "Запись в рабочую область"
      },
      "plan": {
        "chip.exitFailed": "Не удалось выйти из режима планирования",
        "chip.label": "План",
        "chip.off.aria": "Режим планирования выключен, нажмите, чтобы включить",
        "chip.off.title": "Режим планирования выключен — нажмите, чтобы включить (/plan)",
        "chip.on.aria": "Режим планирования включён, нажмите, чтобы выключить",
        "chip.on.title": "Режим планирования включён — нажмите, чтобы выключить (/plan off)"
      },
      "question": {
        "action.next": "Далее",
        "action.skip": "Пропустить этот вопрос",
        "custom.placeholder": "Введите ответ",
        "error.incomplete": "Сначала ответьте на этот вопрос.",
        "error.unanswered": "Выберите вариант или введите свой ответ.",
        "nav.cancel": "Закрыть все вопросы",
        "nav.maximize": "Развернуть карточку вопроса",
        "nav.minimize": "Свернуть карточку вопроса",
        "nav.next": "Следующий вопрос",
        "nav.prev": "Предыдущий вопрос",
        "option.recommended": "Рекомендуется",
        "plan.approve": "Одобрить",
        "plan.decline": "Отклонить",
        "plan.discuss": "Обсудить",
        "plan.header": "Проверка плана"
      },
      "reference": {
        "candidate.noCwd": "(нет рабочей папки)",
        "crumb.root": "Рабочая область",
        "section.files": "Файлы и папки",
        "section.sessions": "Диалоги сессий",
        "time.days": "{n} дн",
        "time.hours": "{n} ч",
        "time.minutes": "{n} мин",
        "time.months": "{n} мес",
        "time.now": "только что",
        "time.years": "{n} г"
      },
      "schedule.catalog": {
        "frequency.every": "Каждые {value} {unit}",
        "frequency.once": "Один раз",
        "list.aria": "Активные напоминания",
        "relative.future": "через {value} {unit}",
        "relative.now": "Уже пора",
        "relative.overdue": "просрочено на {value} {unit}",
        "status.overdue": "Просрочено",
        "status.scheduled": "Запланировано",
        "trigger.one": "{count} напоминание",
        "trigger.other": "{count} напоминаний",
        "unit.day.one": "дн",
        "unit.day.other": "дн",
        "unit.hour.one": "ч",
        "unit.hour.other": "ч",
        "unit.minute.one": "мин",
        "unit.minute.other": "мин",
        "unit.second.one": "с",
        "unit.second.other": "с"
      },
      "session-log-download": {
        "dialog.close": "Закрыть",
        "dialog.commandFailed": "Не удалось начать экспорт сессии.",
        "dialog.errorTitle": "Экспорт сессии не удался",
        "dialog.preparingDescription": "Подготовка ZIP-архива с этой сессией, её подсессиями и вложениями.",
        "dialog.preparingTitle": "Экспорт сессии",
        "dialog.successDescription": "Браузер загружает ZIP-архив сессии.",
        "dialog.successTitle": "Загрузка сессии началась",
        "header.more": "Ещё действия",
        "menu.download": "Скачать журнал сессии"
      },
      "settings": {
        "close": "Закрыть",
        "connection.connected": "Подключено",
        "connection.connecting": "Переподключение",
        "connection.error": "Нет соединения",
        "connection.reconnect": "Нет соединения, переподключиться",
        "connection.restart": "Переподключение выполняется автоматически; переподключиться вручную",
        "connection.retry": "Переподключиться",
        "general.nav": "Общие",
        "openDocument": "Открыть файл конфигурации",
        "openDocument.error": "Не удалось открыть файл конфигурации",
        "title": "Настройки",
        "trigger": "Настройки"
      },
      "settings.agentPreset": {
        "brokenBadge": "Не удалось загрузить",
        "brokenNoCopy": "Не удалось дублировать пресет, который не загрузился",
        "builtIn": "Встроенный",
        "builtInGroup": "Встроенные",
        "cancel": "Отмена",
        "close": "Закрыть",
        "composition": "Композиция (agent.cordis.yml)",
        "copyIntro": "Пресет полностью копируется на этой машине. Идентификатор становится именем каталога и позже не меняется; всё остальное редактируется в собственных файлах пресета.",
        "copyOf": "Скопировано из",
        "copyTitle": "Дублировать пресет",
        "create": "Создать",
        "creating": "Создание…",
        "creatorDraft": "Создать свой пресет в режиме Creator",
        "customGroup": "Свой",
        "delete": "Удалить",
        "deleteConfirm": "Удалить",
        "deleteDescription": "Каталог пресета будет удалён. Уже запущенные на нём сессии продолжат работать; новые сессии не смогут его выбрать.",
        "deleteTitle": "Удалить этот пресет?",
        "deleting": "Удаление…",
        "displayName": "Название",
        "displayNamePlaceholder": "Показывается в списке; по умолчанию — идентификатор",
        "duplicate": "Дублировать",
        "duplicateUnavailable": "В этой установке нет каталога пресетов для записи",
        "error": "Не удалось загрузить пресеты агентов.",
        "headerHint": "Пресет агента, с которым запущена эта сессия (зафиксирован при старте)",
        "idInvalid": "Используйте строчные буквы, цифры и дефисы, начиная с буквы или цифры.",
        "idRequired": "Задайте идентификатор пресета.",
        "idTaken": "Пресет с таким идентификатором уже существует.",
        "inUse": "Используется",
        "nav": "Пресеты агентов",
        "noDescription": "Без описания.",
        "openLocation": "Открыть папку",
        "presetCordisDescription": "Создан для создания собственных пресетов агентов: все возможности режима Standard плюс инспекция среды выполнения, эксперименты с плагинами и подсказки по созданию пресетов.",
        "presetCordisName": "Режим Creator",
        "presetId": "Идентификатор",
        "presetIdPlaceholder": "my-agent",
        "presetMinimalDescription": "Кодинг-агент с двумя инструментами: постоянным bash и str_replace_editor.",
        "presetMinimalName": "Минимальный режим",
        "presetPtcDescription": "Полноценный кодинг-агент без инструмента workflow; остальные инструменты доступны через SDK режима PTC, поэтому модель может объединять многошаговые операции в одной программе на TypeScript.",
        "presetPtcName": "Режим PTC",
        "presetStandardDescription": "Полноценный кодинг-агент: редактирование файлов, терминал, поиск по файлам и вебу, навыки, планирование, цели, субагенты и воркфлоу.",
        "presetStandardName": "Стандартный режим",
        "retry": "Повторить",
        "revealedPathLabel": "Файлы пресета:",
        "seatHint": "Пресет агента для сессии, которую вы собираетесь начать",
        "sectionIntro": "Пресет — это композиция плагинов, с которой работает агент сессии: его инструменты, промпт и возможности. Дублируйте существующий и сделайте своим или попросите агента создать его в режиме Creator.",
        "setDefault": "Сделать по умолчанию",
        "showLocation": "Показать расположение",
        "switchRefused": "Не удалось переключиться на «{name}»: {reason}",
        "userTrust": "Свой",
        "view": "Просмотр"
      },
      "settings.locale": {
        "language.title": "Язык"
      },
      "settings.models": {
        "add": "Добавить провайдера",
        "addModel": "Добавить модель",
        "advancedHint": "Остальные поля находятся в settings.yaml; редактируйте тот раздел напрямую.",
        "apply": "Применить",
        "applying": "Применение…",
        "baseUrl": "Базовый URL",
        "baseUrlDefault": "По умолчанию провайдера",
        "cancel": "Отмена",
        "close": "Закрыть",
        "conflict": "Кто-то ещё изменил эти настройки, пока карточка была открыта. Закройте её и откройте снова, чтобы редактировать актуальные значения.",
        "contextWindow": "Окно контекста",
        "contextWindowPlaceholder": "Использует значение провайдера по умолчанию",
        "create": "Создать провайдера",
        "creating": "Создание…",
        "credentialConfigured": "API-ключ настроен",
        "credentialMissing": "API-ключ отсутствует",
        "customAdd": "Добавить своего провайдера",
        "customApi": "API-протокол",
        "customApiUnset": "Не выбран",
        "customBaseUrlInvalid": "Введите корректный URL с HTTP или HTTPS.",
        "customBaseUrlPlaceholder": "https://gateway.example/v1",
        "customDisplayName": "Отображаемое имя",
        "customNeedsBaseUrl": "Своему провайдеру нужен базовый URL.",
        "customNeedsModels": "Своему провайдеру нужна хотя бы одна модель.",
        "customRoute": "ID провайдера",
        "customRouteHint": "Идентификатор в нижнем регистре, начинается с буквы, уникально именует провайдера в запросах и как имя его учётных данных.",
        "customRouteInvalid": "Начните со строчной буквы; далее строчные буквы, цифры и дефисы.",
        "customRouteTaken": "Этот ID уже использует другой провайдер.",
        "customTag": "Свой",
        "customTitle": "Свой провайдер",
        "customized": "Изменённые настройки",
        "deleteConfirm": "Удалить {provider}",
        "deleteDescription": "Удаление {provider} удалит его конфигурацию. Используемые им учётные данные управляются отдельно и будут сохранены.",
        "deleteDescriptionWithCredential": "Удаление {provider} удалит его конфигурацию и сохранённый API-ключ.",
        "deleteTitle": "Удалить {provider}?",
        "deleting": "Удаление {provider}…",
        "edit": "Изменить",
        "editProvider": "Изменить {provider}",
        "fetchAdopt": "Добавить выбранные",
        "fetchDescription": "Это модели, доступные у этого провайдера. Выберите, какие добавить.",
        "fetchDeselectAll": "Снять выбор",
        "fetchEmpty": "Провайдер не перечислил моделей. Добавьте их вручную.",
        "fetchModels": "Получить доступные модели",
        "fetchNeedsBaseUrl": "Сначала введите базовый URL, затем получите список.",
        "fetchNoMatches": "Подходящих моделей нет.",
        "fetchSearch": "Поиск моделей",
        "fetchSelectAll": "Выбрать все",
        "fetchTitle": "Выберите модели для добавления",
        "fetching": "Запрос к провайдеру…",
        "intro": "Введите API-ключи, чтобы использовать модели следующих провайдеров.",
        "keyBlank": "Введите API-ключ или оставьте поле пустым, чтобы сохранить текущий.",
        "keyBlankNew": "Введите API-ключ или оставьте поле пустым, если провайдер использует другой способ аутентификации.",
        "keyEnvLocked": "Предоставлено средой запуска (только чтение)",
        "keyIllegalCharacters": "API-ключ имеет недопустимый формат. Проверьте его.",
        "keyInput": "API-ключ",
        "keyPlaceholder": "Введите ваш API-ключ",
        "keyPlaceholderNative": "Введите API-ключ или оставьте пустым для аутентификации через окружение",
        "keyRequired": "Введите API-ключ, чтобы продолжить.",
        "keyStored": "Настроен — введите новое значение для замены",
        "loadFailed": "Не удалось загрузить каталог провайдеров",
        "maxTokens": "Макс. выходных токенов",
        "maxTokensPlaceholder": "Использует значение провайдера по умолчанию",
        "model": "Модель",
        "modelAdvanced": "Лимиты",
        "modelCapacityInvalid": "Лимит должен быть числом, при желании с суффиксом K или M.",
        "modelContextInvalid": "Окно контекста должно быть положительным числом, например 131072, 256K или 1M.",
        "modelContextWindow": "Окно контекста",
        "modelDuplicate": "Каждый ID модели может встречаться один раз.",
        "modelId": "ID модели",
        "modelIdDuplicate": "ID модели должен быть уникальным.",
        "modelIdRequired": "Требуется ID модели.",
        "modelMaxTokens": "Макс. выходных токенов",
        "modelMaxTokensInvalid": "Макс. выходных токенов должно быть положительным числом, например 8192, 64K или 1M.",
        "modelName": "Отображаемое имя",
        "modelNameInvalid": "Отображаемое имя не может быть пустым.",
        "modelNamePlaceholder": "Использует ID модели, если пусто",
        "models": "Модели",
        "modelsCustomized": "Изменённый каталог моделей",
        "modelsEmpty": "Ни одна модель не будет показана в селекторе. Не перечисленные ID всё ещё можно отправлять напрямую.",
        "modelsInherited": "Используются настройки адаптера по умолчанию",
        "nav": "Модели",
        "onboardingDescription": "Настройте официального провайдера DeepSeek, чтобы начать работу.",
        "onboardingLater": "Настроить позже",
        "onboardingSave": "Сохранить и продолжить",
        "onboardingSaving": "Сохранение…",
        "onboardingTitle": "Добавьте API-ключ, чтобы начать",
        "provider": "Провайдер",
        "readOnly": "Документ настроек доступен только для чтения в этой установке.",
        "remove": "Удалить",
        "removeModel": "Удалить модель",
        "removeProvider": "Удалить {provider}",
        "resetModels": "Вернуть по умолчанию",
        "retry": "Повторить",
        "savedProvider": "Сохранено: {provider}.",
        "settingsPathUnresolvable": "путь к настройкам не найден",
        "title": "Модели",
        "welcomeBody": "DeepSeek Harness 0.1 остаётся в статусе тестирования для разработчиков Harness. Многие области требуют доработки, и мы приветствуем отзывы сообщества разработчиков. Основные плагины и базовые API DeepSeek Harness продолжат быстро развиваться в ближайшие месяцы.\n\nМы рассчитываем вместе с разработчиками со всего мира исследовать пределы интеллекта, опираясь на открытую, доступную для переиспользования и компонуемую инфраструктуру. Приглашаем разработчиков Harness со всего мира присоединиться к экосистеме плагинов DSH.",
        "welcomeContinue": "Продолжить",
        "welcomeError": "Не удалось сохранить подтверждение. Попробуйте снова.",
        "welcomeTitle": "Уведомление о внутреннем тестировании"
      },
      "settings.permission": {
        "confirm.acknowledge": "Я понимаю риски и хочу продолжить",
        "confirm.cancel": "Отмена",
        "confirm.description": "Полный доступ позволяет новым сессиям сократить шаги подтверждения и выполнять больше действий напрямую, включая чувствительные операции, изменения файлов и внешние команды. Используйте его, только если доверяете последующим задачам.",
        "confirm.enable": "Включить полный доступ",
        "confirm.title": "Включить полный доступ?",
        "description": "Выберите режим разрешений по умолчанию для новых сессий",
        "loading": "Загрузка",
        "preset.fullAccess": "Полный доступ",
        "preset.readOnly": "Только чтение",
        "preset.workspaceWrite": "Запись в рабочую область",
        "title": "Разрешения",
        "unavailable": "Недоступно"
      },
      "settings.pluginInventory": {
        "active": "Подключено",
        "condition": "Отключён, если",
        "conditionalTag": "Условный",
        "configuration": "Конфигурация",
        "countUnit": "плагинов",
        "disabledTag": "Отключено",
        "empty": "Нет доступных плагинов.",
        "emptySearch": "Нет подходящих плагинов.",
        "enabledIn": "Включён в",
        "enabledTag": "Включено",
        "error": "Плагины временно недоступны.",
        "failed": "Не удалось подключить",
        "failedCountLabel": "с ошибкой",
        "failedTag": "Не удалось",
        "fromPreset": "Из",
        "globalSubtitle": "Общие для системы и всех сессий",
        "globalTitle": "Глобальные плагины",
        "loading": "Чтение плагинов…",
        "loadingPhase": "Загрузка",
        "matchesInOtherPresets": "{count} ещё совпадений в других пресетах: ",
        "moduleLabel": "Модуль",
        "pending": "Ожидание зависимостей",
        "presetEnabledTag": "Включён через пресеты",
        "presetOptionBroken": "{name} (не загрузился)",
        "presetOptionDefault": "{name} (по умолчанию)",
        "presetProvidedDetail": "Отключён глобально; пресеты агентов подключают его в каждой сессии",
        "presetSubtitle": "Собираются в каждой сессии пресетами агентов",
        "presetTitle": "Плагины сессии",
        "retry": "Повторить",
        "runtime": "Статус",
        "search": "Поиск плагинов",
        "switcherLabel": "Выберите пресет агента для просмотра",
        "tab": "Список плагинов",
        "unloading": "Отключение",
        "unobserved": "Не подключено",
        "viewInPreset": "Показать в группе пресета"
      },
      "settings.plugins": {
        "agentLoopDescription": "Как агент распределяет вызовы инструментов.",
        "agentLoopMaxParallel": "Параллельные вызовы инструментов",
        "agentLoopMaxParallelHint": "Верхний предел параллельно-безопасных вызовов, выполняющихся одновременно в одном шаге.",
        "agentLoopTitle": "Цикл агента",
        "bashDescription": "Ограничения для каждой команды, которую выполняет агент.",
        "bashMaxOutputBytes": "Лимит вывода на поток (байты)",
        "bashMaxOutputBytesHint": "Вывод сверх лимита сохраняется во временный файл, а не теряется.",
        "bashTimeoutMs": "Таймаут команды (мс)",
        "bashTimeoutMsHint": "Сколько может выполняться команда до её завершения.",
        "bashTitle": "Терминал",
        "collapse": "Скрыть настройки",
        "configurableTab": "Конфигурация плагинов",
        "discard": "Отменить",
        "empty": "Эта установка не предоставляет настроек плагинов.",
        "expand": "Показать настройки",
        "intro": "Настройка и просмотр плагинов, установленных в этой установке.",
        "invalidNumber": "Введите число или оставьте пустым, чтобы использовать значение по умолчанию.",
        "nav": "Плагины",
        "overridden": "Переопределено",
        "readOnly": "Эта установка хранит настройки только для чтения.",
        "reset": "Сбросить на значение по умолчанию",
        "save": "Сохранить",
        "saveFailed": "Установка не приняла эти значения; они оставлены для исправления.",
        "saving": "Сохранение…",
        "subagentModelSelectionAllowed": "Модели, доступные агентам",
        "subagentModelSelectionChoose": "Когда включено, агенты могут выбирать провайдера, модель и усилия рассуждения для каждого субагента из разрешённых ниже моделей. Действует только для новых сессий.",
        "subagentModelSelectionConflict": "Настройки изменились в другом месте. Отмените черновик и попробуйте снова.",
        "subagentModelSelectionDescription": "Определяет, какие модели агенты могут выбирать для субагентов.",
        "subagentModelSelectionEmpty": "Ни один провайдер моделей сейчас не сообщает о моделях.",
        "subagentModelSelectionLoadFailed": "Не удалось загрузить модели.",
        "subagentModelSelectionLoading": "Загрузка моделей…",
        "subagentModelSelectionOff": "Субагенты используют настроенные значения по умолчанию или наследуют модель родительского агента. Сохранённые выборы моделей сохраняются.",
        "subagentModelSelectionPartial": "Часть провайдеров моделей не загрузилась; сохранённые выборы можно удалить.",
        "subagentModelSelectionRequired": "Выберите хотя бы одну модель перед сохранением.",
        "subagentModelSelectionRetry": "Повторить",
        "subagentModelSelectionTitle": "Субагент",
        "subagentModelSelectionToggle": "Разрешить агентам выбирать модели для субагентов",
        "subagentModelSelectionUnavailable": "Сейчас недоступно",
        "subagentModelSelectionUnavailableGroup": "Сохранено, но сейчас недоступно",
        "tabs": "Разделы плагинов",
        "title": "Плагины",
        "unsaved": "Не сохранено",
        "webSearchApiKey": "API-ключ",
        "webSearchApiKeyHint": "Хранится вне файла настроек. Оставьте пустым, чтобы сохранить текущий ключ.",
        "webSearchApiKeySet": "Ключ настроен.",
        "webSearchApiKeyUnset": "Ключ не настроен; поиск недоступен, пока его нет.",
        "webSearchBaseUrl": "Конечная точка",
        "webSearchBaseUrlHint": "Оставьте пустым, чтобы использовать значение провайдера по умолчанию.",
        "webSearchDescription": "Поисковый провайдер DeepSeek.",
        "webSearchMaxUses": "Макс. поисков за запрос",
        "webSearchMaxUsesHint": "Сколько раз один запрос может выполнять поиск, прежде чем ответить.",
        "webSearchTitle": "Веб-поиск"
      },
      "settings.theme": {
        "appearance.dark": "Тёмная",
        "appearance.light": "Светлая",
        "appearance.system": "Системная",
        "appearance.title": "Оформление",
        "fontSize.decrease": "Уменьшить размер шрифта",
        "fontSize.description": "Влияет только на содержимое диалога",
        "fontSize.increase": "Увеличить размер шрифта",
        "fontSize.title": "Размер шрифта",
        "fontSize.unit": "px"
      },
      "sidebar": {
        "panels.label": "Глобальные панели",
        "session.new": "Новая сессия",
        "session.new.label": "Новая сессия",
        "toggle.collapse": "Свернуть боковую панель",
        "toggle.open": "Открыть боковую панель"
      },
      "sidebarCodePreview": {
        "copied": "Скопировано",
        "copy": "Копировать",
        "title": "Код"
      },
      "sidebarDocumentPreview": {
        "changed": "Файл изменился, показано предыдущее содержимое.",
        "error.notFound": "Файл не найден. Возможно, он перемещён или удалён.",
        "error.notRegularFile": "Это не обычный файл, показывать нечего.",
        "error.notText": "Это не текстовый файл, предпросмотр пока недоступен.",
        "error.tooLarge": "Эта страница превышает лимит {limit} и не может быть прочитана.",
        "error.unavailable": "Не удалось прочитать: {message}",
        "loadMore": "Загрузить ещё",
        "loading": "Чтение…",
        "openWith": "Открыть с помощью",
        "reload": "Прочитать файл заново",
        "reloadNow": "Перезагрузить",
        "rendererUnavailable": "Предпросмотр {name} недоступен.",
        "resourceUnavailable": "Служба файловых ресурсов недоступна.",
        "retry": "Повторить",
        "viewer.text": "Обычный текст",
        "wrap.aria": "Перенос строк",
        "wrap.disable": "Отключить перенос строк",
        "wrap.enable": "Включить перенос строк"
      },
      "sidebarFiles": {
        "empty": "Пустой каталог",
        "entry.other": "Это не файл и не папка, поэтому открыть нельзя.",
        "error.notDirectory": "Это не папка.",
        "error.notFound": "Папка исчезла. Возможно, она перемещена или удалена.",
        "error.outsideWorkspace": "Эта папка вне рабочей области, поэтому боковая панель её не читает.",
        "error.unavailable": "Не удалось прочитать: {message}",
        "guide.description": "Просмотр файлов рабочей области этой сессии",
        "guide.title": "Файлы рабочей области",
        "loading": "Чтение…",
        "noWorkspace": "У этой сессии нет папки рабочей области.",
        "reload": "Перезагрузить",
        "truncated": "Слишком много элементов, показана только часть.",
        "type.label": "Файлы"
      },
      "sidebarImage": {
        "failed": "Не удалось отобразить это изображение.",
        "loading": "Открытие изображения…",
        "preview": "Предпросмотр изображения: {name}",
        "title": "Изображение",
        "unsupported": "Для предпросмотра изображения нужен полный файл."
      },
      "sidebarPdf": {
        "failed": "Не удалось показать PDF: {message}",
        "loading": "Открытие PDF…",
        "pageImage": "Страница PDF {page}",
        "password": "Для этого PDF нужен пароль; предпросмотр файлов с паролем не поддерживается.",
        "rendering": "Отрисовка страницы…",
        "retry": "Повторить",
        "title": "PDF",
        "unsupported": "Для предпросмотра PDF нужен полный файл.",
        "workerFailed": "Процесс отрисовки PDF не смог продолжиться. Повторите попытку."
      },
      "sidebarRight": {
        "chrome.collapse": "Свернуть боковую панель",
        "chrome.collapseAria": "Свернуть правую панель",
        "chrome.exitFullscreen": "Выйти из полноэкранного режима",
        "chrome.expand": "Открыть боковую панель",
        "chrome.expandAria": "Открыть правую панель",
        "chrome.toFullscreen": "Полный экран",
        "dock.addTab": "Новая вкладка",
        "dock.closeFloat": "Закрыть",
        "dock.closeTab": "Закрыть",
        "dock.dockFloat": "Вернуть в боковую панель",
        "dock.drop.bottom": "Добавить разделение снизу",
        "dock.drop.center": "Переместить сюда",
        "dock.drop.left": "Добавить разделение слева",
        "dock.drop.right": "Добавить разделение справа",
        "dock.drop.top": "Добавить разделение сверху",
        "dock.emptyPane": "Пустая область",
        "dock.splitPane": "Разделить",
        "dock.splitPaneDisabled": "Максимум две области",
        "dock.splitPaneNarrow": "Недостаточно ширины для разделения — расширьте боковую панель",
        "tab.guide.title": "Начало",
        "tab.unavailable": "Здесь пока нечем открыть такой тип содержимого."
      },
      "skill": {
        "menu.userOnly": "только для пользователя",
        "row.failed": "Не удалось загрузить навык",
        "row.inspect": "Просмотр",
        "row.instructions": "Инструкции",
        "row.running": "Загрузка навыка",
        "row.stopped": "Загрузка навыка остановлена",
        "row.title": "Навык"
      },
      "slash.menu": {
        "command": "Команды",
        "crumbs.aria": "Навигация по папкам",
        "drill.aria": "Просмотр папки",
        "drill.hint": "Просмотр папки",
        "drill.key": "Tab",
        "loading": "Загрузка…",
        "skill": "Навыки",
        "subagent": "Субагенты",
        "suggestions.aria": "Подсказки команд"
      },
      "subagent": {
        "activity.inactive": "не выполняется",
        "activity.running": "выполняется",
        "branch.collapse": "Свернуть подчинённые элементы {label}",
        "branch.expand": "Развернуть подчинённые элементы {label}",
        "count.running.one": "Выполняется {count} субагент",
        "count.running.other": "Выполняется {count} субагентов",
        "count.total.one": "{count} субагент",
        "count.total.other": "{count} субагентов",
        "diagnostic.corrupt": "повреждённая запись сессии",
        "diagnostic.unavailable": "запись сессии временно недоступна",
        "diagnostic.unsupported": "неподдерживаемая версия записи субагента",
        "duration.days": "{days} дн",
        "duration.daysHours": "{days} дн {hours} ч",
        "duration.exactDays": "{days} дн {hours} ч {minutes} мин {seconds} с",
        "duration.exactTitle": "Общая продолжительность: {duration}",
        "duration.hours": "{hours} ч {minutes} мин {seconds} с",
        "duration.minutes": "{minutes} мин {seconds} с",
        "duration.months": "~{months} мес",
        "duration.monthsDays": "~{months} мес {days} дн",
        "duration.seconds": "{seconds} с",
        "duration.years": "~{years} г",
        "duration.yearsMonths": "~{years} г {months} мес",
        "load.error": "Не удалось загрузить субагентов",
        "loading.aria": "Загрузка субагентов",
        "loading.label": "Загрузка субагентов…",
        "mode.continuable": "продолжаемый",
        "mode.oneShot": "одноразовый",
        "readonly.body": "Родительская сессия недоступна; откройте её, чтобы продолжить отправку сообщений.",
        "readonly.oneShot.body": "Одноразовые задачи не принимают уточнений; просмотрите полную запись выполнения здесь.",
        "readonly.oneShot.title": "Запись одноразового субагента",
        "readonly.title": "Этот субагент сейчас доступен только для чтения",
        "retry": "Повторить",
        "switcher.aria": "Переключить субагента: {title}",
        "tokens.million": "{value} млн",
        "tokens.thousand": "{value} тыс.",
        "tokens.total": "{value} ток.",
        "tree.aria": "Сессии субагентов"
      },
      "trajectory": {
        "block.label": "Блок #{index} {type}",
        "block.openSummary": "Открыть сводку вызовов инструментов блока #{index}",
        "block.openSummaryTitle": "Открыть сводку вызовов инструментов",
        "column.input": "Ввод",
        "column.model": "Модель",
        "column.output": "Вывод",
        "column.think": "Рассуждение",
        "column.time": "Время",
        "column.tools": "Инструменты",
        "details.assistantMessage": "Сообщение ассистента",
        "details.close": "Закрыть подробности",
        "details.compacted": "Сжато",
        "details.error": "Ошибка",
        "details.event": "Подробности события",
        "details.failure.auth": "API-ключ недействителен",
        "details.hierarchy": "Иерархия",
        "details.model": "Модель",
        "details.provider": "Провайдер",
        "details.purpose": "Назначение",
        "details.resize": "Изменить размер подробностей события",
        "details.resizeTitle": "Перетащите, чтобы изменить размер. Двойной щелчок — сбросить.",
        "details.result": "Результат",
        "details.retry": "Повторить",
        "details.retryDelay": "Задержка повтора",
        "details.scheduled": "Запланировано",
        "details.source": "Источник",
        "details.status": "Статус",
        "details.subtoolCalls": "Вызовы вложенных инструментов",
        "details.toolCall": "Вызов инструмента",
        "details.toolCalls": "Вызовы инструментов",
        "group.compaction": "Сжатие {seq}",
        "group.message": "Сообщение",
        "group.step": "Этап {step}",
        "history.clickToLoadEarlier": "Нажмите, чтобы загрузить более раннюю историю",
        "history.loadEarlier": "Загрузить более раннюю историю",
        "history.loadingEarlier": "Загрузка более ранней истории…",
        "history.loadingEarlierAria": "Загрузка более ранней истории…",
        "history.loadingTrajectory": "Загрузка траектории…",
        "kind.assistant": "АССИСТЕНТ",
        "kind.compacted": "СЖАТО",
        "kind.context": "КОНТЕКСТ",
        "kind.message": "СООБЩЕНИЕ",
        "kind.sub": "ПОДЭЛЕМЕНТ",
        "kind.subtool": "СУБИНСТРУМЕНТ",
        "kind.system": "СИСТЕМА",
        "kind.tool": "ИНСТРУМЕНТ",
        "kind.user": "ПОЛЬЗОВАТЕЛЬ",
        "layout.compacted": "Контекст сжат",
        "layout.compacting": "Сжатие контекста…",
        "layout.compactionFailed": "Не удалось сжать контекст",
        "layout.compactionInterrupted": "Сжатие было прервано до завершения.",
        "layout.fileAttachments": "Файлы ×{count}",
        "layout.imageOnly": "Изображения ×{count}",
        "layout.initialSystemPrompt": "Исходный системный промпт",
        "layout.systemPromptAndToolsUpdated": "Системный промпт и инструменты обновлены",
        "layout.systemPromptUpdated": "Системный промпт обновлён",
        "layout.toolCallOnly": "Только вызов инструмента",
        "layout.toolsUpdated": "Инструменты обновлены",
        "options.json": "JSON параметров запроса",
        "options.notRecorded": "Параметры не записаны",
        "record.json": "JSON",
        "record.namedParametersJson": "JSON параметров {name}",
        "record.noContent": "Нет содержимого",
        "record.noOutput": "Нет вывода",
        "record.noPayload": "Тело запроса не записано",
        "record.noResult": "Результат не записан",
        "record.outputJson": "JSON результата",
        "record.parameters": "Параметры",
        "record.parametersJson": "JSON параметров",
        "record.payloadJson": "JSON тела запроса",
        "record.resultJson": "JSON результата",
        "record.schemaUnavailable": "Схема недоступна",
        "record.systemPrompt": "Системный промпт",
        "record.systemPromptMissing": "В этом запросе нет системного промпта",
        "record.thinking": "Рассуждение",
        "record.toolCallOnly": "(только вызов инструмента)",
        "record.tools": "Инструменты",
        "record.toolsMissing": "В этом запросе нет инструментов",
        "request.collapsedAssistant": "ассистент",
        "request.collapsedSummary": "Сводка {kind} свёрнута, {summary}",
        "request.collapsedTurn": "шаг",
        "request.compaction": "Сжатие · {section}",
        "request.compactionPurpose": "Сжатие",
        "request.label": "Запрос #{request}",
        "request.labelCompaction": "Запрос #{request} · Сжатие",
        "request.noContent": "нет содержимого",
        "request.retryProgress": "{retry} из {maximum}",
        "request.rowAria": "{request}{kind}, {content}",
        "request.rowAriaCompaction": "Запрос {request}, сжатие",
        "request.rowPrefix": "Запрос {request}, ",
        "section.betweenTurns": "Между шагами",
        "source.goal": "Цель",
        "source.goalRound": "Цель · раунд {round}",
        "source.messageJson": "JSON источника сообщения",
        "source.notRecorded": "Источник не записан",
        "source.plugin": "Плагин",
        "source.pluginNamed": "Плагин · {plugin}",
        "source.unknown": "Неизвестно",
        "source.user": "Пользователь",
        "status.completed": "Завершено",
        "status.failed": "Не удалось",
        "status.pending": "Ожидание",
        "summary.steps.one": "{count} этап",
        "summary.steps.other": "{count} этапов",
        "summary.toolCalls.one": "{count} вызов инструмента",
        "summary.toolCalls.other": "{count} вызовов инструментов",
        "tab.diff": "Дифф",
        "tab.options": "Параметры",
        "tab.payload": "Тело запроса",
        "tab.preview": "Предпросмотр",
        "tab.raw": "Исходный",
        "tab.rawOutput": "Исходный вывод",
        "tab.result": "Результат",
        "tab.schema": "Схема",
        "tab.source": "Источник",
        "tab.summary": "Сводка",
        "tab.systemPrompt": "Системный промпт",
        "tab.timing": "Тайминги",
        "tab.tools": "Инструменты",
        "tab.usage": "Использование",
        "timeline.aria": "Шкала траектории",
        "timeline.noTimingData": "Нет данных о таймингах",
        "timeline.overviewAria": "Обзор шкалы; перетащите по горизонтали, чтобы перейти к нужным событиям",
        "timeline.started": "Начало {time}",
        "timeline.total": "Всего {duration}",
        "timeline.ttftDecoding": "TTFT {ttft} · генерация {decoding}",
        "timing.duration": "Продолжительность",
        "timing.durationTooShort": "Слишком маленькая длительность",
        "timing.firstTokenUnavailable": "Первый токен недоступен",
        "timing.generation": "Генерация",
        "timing.notAvailable": "Недоступно",
        "timing.notRecorded": "Не записано",
        "timing.outputTokensUnavailable": "Выходные токены недоступны",
        "timing.request": "Тайминги запроса",
        "timing.sessionTimestamps": "Метки времени сессии",
        "timing.sessionTimestampsRunning": "Метки времени сессии (идёт выполнение)",
        "timing.showLocalTime": "Показывать местное время",
        "timing.showUnixTimestamp": "Показывать метку времени Unix",
        "timing.source": "Источник таймингов",
        "timing.started": "Начало",
        "timing.stepStartUnavailable": "Начало этапа недоступно",
        "timing.throughput": "Пропускная способность",
        "timing.totalDuration": "Общая длительность",
        "timing.ttft": "TTFT",
        "timing.usageUnavailable": "Данные об использовании недоступны",
        "toolbar.actualTime": "Фактическое время",
        "toolbar.aria": "Панель траектории",
        "toolbar.calls": "Вызовы",
        "toolbar.collapseCalls": "Свернуть вызовы",
        "toolbar.collapseTurns": "Свернуть шаги",
        "toolbar.duration": "Продолжительность",
        "toolbar.expandCalls": "Развернуть вызовы",
        "toolbar.expandTurns": "Развернуть шаги",
        "toolbar.search": "Поиск по траектории",
        "toolbar.searchPlaceholder": "Поиск",
        "toolbar.turns": "Шаги",
        "toolbar.useActualDuration": "Использовать фактическую продолжительность",
        "toolbar.useEqualWidth": "Равная ширина операций",
        "turn.label": "Шаг {turn}",
        "unit.milliseconds": "{value} мс",
        "unit.seconds": "{value} с",
        "unit.tokens": "{value} ток.",
        "unit.tokensPerSecond": "{value} ток./с",
        "usage.cacheCreated": "Создано в кэше",
        "usage.cached": "Из кэша",
        "usage.content": "Содержимое",
        "usage.input": "Ввод",
        "usage.notReported": "Использование не указано",
        "usage.other": "Прочее",
        "usage.output": "Вывод",
        "usage.reasoning": "Рассуждение",
        "usage.sessionCumulative": "Всего за сессию",
        "usage.thisRequest": "Этот запрос",
        "usage.tokens": "Токены",
        "view.trajectory": "Траектория"
      },
      "workflowRun": {
        "member.empty": "Пустое имя участника",
        "member.open": "Открыть {name}",
        "phase.empty": "Пустое имя фазы",
        "phase.unassigned": "Без фазы",
        "run.empty": "Участники не запущены",
        "run.members.one": "{count} участник",
        "run.members.other": "{count} участников",
        "run.title": "{name}",
        "status.cancelled": "Отменено",
        "status.completed": "Завершено",
        "status.failed": "Не удалось",
        "status.interrupted": "Прервано",
        "status.running": "Выполняется",
        "statusCount.cancelled": "Отменено: {count}",
        "statusCount.completed": "Завершено: {count}",
        "statusCount.failed": "Не удалось: {count}",
        "statusCount.interrupted": "Прервано: {count}",
        "statusCount.running": "Выполняется: {count}"
      },
      "workspace": {
        "actions.newSession.aria": "Новая сессия в {name}",
        "actions.session.aria": "Действия с сессией {name}",
        "actions.workspace.aria": "Действия с рабочей областью {name}",
        "conflict.named": "Рабочая область «{name}» уже существует.",
        "date.ymd": "{y}-{m}-{d}",
        "delete.desc": "Это удалит «{name}» из списка рабочих областей. Папка и журналы сессий будут сохранены. Её сессии появятся в разделе «Без группы».",
        "delete.pending": "Удаление рабочей области…",
        "delete.workspace": "Удалить рабочую область",
        "empty.noMatches": "Ничего не найдено",
        "empty.none": "Сессий пока нет",
        "field.sessionName": "Имя сессии",
        "field.workspaceName": "Имя рабочей области",
        "folderError.retry": "Выбрать снова",
        "folderError.title": "Не удалось открыть папку",
        "group.ungrouped": "Без группы",
        "groupBy.flat": "Одним списком",
        "groupBy.label": "Группировать по",
        "groupBy.workspace": "Рабочая область",
        "hover.copied": "Скопировано",
        "hover.created": "Создано {time}",
        "menu.addWorkspace": "Добавить рабочую область…",
        "menu.archiveSession": "Архивировать сессию",
        "menu.fork": "Разветвить сессию",
        "orderBy.label": "Сортировать по",
        "orderBy.manual": "Вручную",
        "orderBy.updated": "По дате изменения",
        "picker.loading": "Загрузка рабочих областей…",
        "rename": "Переименовать",
        "rename.session.title": "Переименовать сессию",
        "rename.workspace.title": "Переименовать рабочую область",
        "schedule.active": "Есть активная задача по расписанию",
        "search.clear": "Очистить поиск",
        "search.hasMore": "Показаны первые {n} результатов. Уточните поиск.",
        "search.noMatches": "Сессии не найдены",
        "search.pending": "Поиск по истории сессий…",
        "search.placeholder": "Поиск сессий...",
        "search.results.aria": "Результаты поиска",
        "search.sessions.aria": "Поиск сессий",
        "search.unavailable": "Поиск по содержимому временно недоступен. Показаны совпадения по имени.",
        "section.sessions": "Сессии",
        "section.workspaces": "Рабочие области",
        "session.new": "Новая сессия",
        "sessions.collapse": "Показать меньше",
        "sessions.count.one": "{n} сессия",
        "sessions.count.other": "{n} сессий",
        "sessions.expand": "Показать ещё {n} сессий",
        "status.completed": "Завершено",
        "status.idle": "Ожидает",
        "status.planReview": "План ожидает проверки",
        "status.running": "Выполняется",
        "status.subagentsRunning.one": "Выполняется {n} субагент",
        "status.subagentsRunning.other": "Выполняется {n} субагентов",
        "status.waitingAnswer": "Ожидание ответа",
        "status.waitingApproval": "Ожидание одобрения",
        "time.ago": "{t} назад",
        "time.days": "{n} дн",
        "time.hours": "{n} ч",
        "time.minutes": "{n} мин",
        "time.months": "{n} мес",
        "time.now": "только что",
        "time.years": "{n} г",
        "viewOptions.label": "Параметры просмотра",
        "workspace.add": "Добавить рабочую область"
      }
    }

    exports.name = 'dsh-locale-ru'
    exports.inject = ['locale']

    exports.apply = function (ctx) {
      var locale = ctx.locale
      if (!locale) return

      // 1. Регистрируем язык: он появляется в списке Settings -> General ->
      //    Language, а регистрация языка сразу пересчитывает активную локаль —
      //    поэтому русский включается сам, если его выбрали в настройках или
      //    просит браузер.
      ctx.effect(function () {
        return locale.addLanguage({
          id: LOCALE_ID,
          label: LOCALE_LABEL,
          fallback: FALLBACK_ID
        })
      }, 'dsh-locale-ru: language')

      // 2. Регистрируем словари. Жизненный цикл привязан к плагину: при выгрузке
      //    переводы снимаются и активный язык возвращается к доступному.
      //    Занятое другим плагином пространство имён пропускаем: лучше показать
      //    его фолбэк, чем не загрузить интерфейс целиком.
      ctx.effect(function () {
        var disposers = []
        Object.keys(RU).forEach(function (namespace) {
          try {
            disposers.push(locale.register(namespace, LOCALE_ID, RU[namespace]))
          } catch (error) {
            console.warn('[dsh-locale-ru] namespace "' + namespace + '" is not registered:', error)
          }
        })
        return function () {
          disposers.forEach(function (dispose) {
            if (dispose) dispose()
          })
        }
      }, 'dsh-locale-ru: dictionaries')

      // 3. Одноразовый перенос выбора из версий 0.1.x: тогда язык хранился в
      //    localStorage (схема настроек хоста принимала только zh/en). Переносим
      //    выбор в settings.yaml и убираем старый ключ, чтобы ничего не потерять.
      try {
        if (localStorage.getItem(LEGACY_PREF_KEY) === LOCALE_ID) {
          localStorage.removeItem(LEGACY_PREF_KEY)
          window.setTimeout(function () {
            try {
              if (locale.getSnapshot().active !== LOCALE_ID) locale.setLocale(LOCALE_ID)
            } catch (error) {
              // Не удалось — язык всегда можно выбрать вручную в настройках.
            }
          }, 0)
        }
      } catch (error) {
        // localStorage недоступен (приватный режим) — переносить нечего.
      }
    }

    return module.exports
  }
})
